/*
 * insertRealmList.sql
 *
 * Copyright (C) 2008 - 2011 by Joshua S. English. This document is the
 * intellectual property of Joshua S. English, all rights reserved.
 *
 * The list of realms for the World of Warcraft (WoW) Combat Performance
 * Reports (CPR) website.
 *
 * Written by Josh English.
 */

---
--- World of Warcraft - European, English-Speaking Realms
---

insert into cprRealm (region, name, language, type) values ('EU', 'Aerie Peak', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Agamaggan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Aggramar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Ahn''Qiraj', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Al''Akir', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Alonsus', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Anachronos', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Arathor', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Argent Dawn', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Aszune', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Auchindoun', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Azjol-Nerub', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Azuremyst', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Balnazzar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Blade''s Edge', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Bladefist', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Bloodfeather', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Bloodhoof', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Bloodscalp', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Boulderfist', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Bronze Dragonflight', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Bronzebeard', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Burning Blade', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Burning Legion', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Burning Steppes', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Chamber of Aspects', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Chromaggus', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Crushridge', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Daggerspine', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Darkmoon Faire', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Darksorrow', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Darkspear', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Deathwing', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Defias Brotherhood', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dentarg', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Doomhammer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Draenor', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Dragonblight', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Dragonmaw', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Drak''thul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dunemaul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Earthen Ring', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Emerald Dream', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Emeriss', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Eonar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Executus', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Frostmane', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Frostwhisper', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Genjuros', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ghostlands', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Grim Batol', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Hakkar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Haomarush', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Hellfire', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Hellscream', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Jaedenar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Karazhan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Kazzak', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Khadgar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Kilrogg', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Kor''gall', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Kul Tiras', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Laughing Skull', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Lightbringer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Lightning''s Blade', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Magtheridon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Mazrigos', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Moonglade', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nagrand', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Neptulon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nordrassil', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Outland', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Quel''Thalas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Ragnaros', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ravencrest', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ravenholdt', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Runetotem', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Saurfang', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Scarshield Legion', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Shadowsong', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Shattered Halls', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Shattered Hand', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Silvermoon', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Skullcrusher', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Spinebreaker', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Sporeggar', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Steamwheedle Cartel', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Stormrage', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Stormreaver', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Stormscale', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Sunstrider', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Sylvanas', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Talnivarr', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Tarren Mill', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Terenas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Terokkar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'The Maelstrom', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'The Sha''tar', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'The Venture Co.', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Thunderhorn', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Trollbane', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Turalyon', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Twilight''s Hammer', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Twisting Nether', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Vashj', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Vek''nilash', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Wildhammer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Xavius', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Zenedar', 'English', 'PvP');

---
--- World of Warcraft - European, German-Speaking Realms
---

insert into cprRealm (region, name, language, type) values ('EU', 'Aegwynn', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Alexstrasza', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Alleria', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Aman''Thul', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Ambossar', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Anetheron', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Antonidas', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Anub''arak', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Area 52', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Arthas', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Arygos', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Azshara', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Baelgun', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Blackhand', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Blackmoore', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Blackrock', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Blutkessel', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dalvengyr', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Das Konsortium', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Das Syndikat', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Der abyssische Rat', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Der Mithrilorden', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Der Rat von Dalaran', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Destromath', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dethecus', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die Aldor', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die Arguswacht', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die ewige Wacht', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die Nachtwache', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die Silberne Hand', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Die Todeskrallen', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dun Morogh', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Durotan', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Echsenkessel', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Eredar', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Festung der Sturme', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Forscherliga', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Frostmourne', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Frostwolf', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Garrosh', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Gilneas', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Gorgonnash', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Gul''dan', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Kargath', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Kel''Thuzad', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Khaz''goroth', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Kil''Jaeden', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Krag''jin', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Kult der Verdammten', 'German', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Lordaeron', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Lothar', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Madmortem', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Mal''Ganis', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Malfurion', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Malorne', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Malygos', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Mannoroth', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Mug''thol', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nathrezim', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nazjatar', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nefarian', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nera''thor', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Nethersturm', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Norgannon', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Nozdormu', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Onyxia', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Perenolde', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Proudmoore', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Rajaxx', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Rexxar', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Sen''jin', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Shattrath', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Taerar', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Teldrassil', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Terrordar', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Theradras', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Thrall', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Tichondrius', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Tirion', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Todeswache', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ulduar', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Un''Goro', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Vek''lor', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Wrathbringer', 'German', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ysera', 'German', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Zirkel des Cenarius', 'German', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Zuluhed', 'German', 'PvP');

---
--- World of Warcraft - European, French-Speaking Realms
---

insert into cprRealm (region, name, language, type) values ('EU', 'Arak-arahm', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Arathi', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Archimonde', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Chants eternels', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Cho''gall', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Confrerie du Thorium', 'French', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Conseil des Ombres', 'French', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Culte de la Rive noire', 'French', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dalaran', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Drek''Thar', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Eitrigg', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Eldre''Thalas', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Elune', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Garona', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Hyjal', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Illidan', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Kael''thas', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Khaz Modan', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Kirin Tor', 'French', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Krasus', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'La Croisade ecarlate', 'French', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Les Clairvoyants', 'French', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Les Sentinelles', 'French', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Marecage de Zangar', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Medivh', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Naxxramas', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Ner''zhul', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Rashgarroth', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Sargeras', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Sinstralis', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Suramar', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Temple noir', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Throk''Feroth', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Uldaman', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Varimathras', 'French', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Vol''jin', 'French', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Ysondre', 'French', 'PvP');

---
--- World of Warcraft - European, Spanish-Speaking Realms
---

insert into cprRealm (region, name, language, type) values ('EU', 'C''Thun', 'Spanish', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Dun Modr', 'Spanish', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Exodar', 'Spanish', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Los Errantes', 'Spanish', 'RP');
insert into cprRealm (region, name, language, type) values ('EU', 'Minahonda', 'Spanish', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Sanguino', 'Spanish', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Shen''dralar', 'Spanish', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Tyrande', 'Spanish', 'Normal');
insert into cprRealm (region, name, language, type) values ('EU', 'Uldum', 'Spanish', 'PvP');
insert into cprRealm (region, name, language, type) values ('EU', 'Zul''Jin', 'Spanish', 'PvP');

---
--- World of Warcraft - U.S.A. Realms
---

insert into cprRealm (region, name, language, type) values ('US', 'Aegwynn', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Aerie Peak', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Agamaggan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Aggramar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Akama', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Alexstrasza', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Alleria', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Altar of Storms', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Alterac Mountains', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Aman''Thul', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Andorhal', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Anetheron', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Antonidas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Anub''arak', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Anvilmar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Arathor', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Archimonde', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Area 52', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Argent Dawn', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Arthas', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Arygos', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Auchindoun', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Azgalor', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Azjol-Nerub', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Azshara', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Azuremyst', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Baelgun', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Balnazzar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Barthilas', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Black Dragonflight', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Blackhand', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Blackrock', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Blackwater Raiders', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Blackwing Lair', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Blade''s Edge', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Bladefist', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Bleeding Hollow', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Blood Furnace', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Bloodhoof', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Bloodscalp', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Bonechewer', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Borean Tundra', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Boulderfist', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Bronzebeard', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Burning Blade', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Burning Legion', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Caelestrasz', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Cairne', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Cenarion Circle', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Cenarius', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Cho''gall', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Chromaggus', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Coilfang', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Crushridge', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Daggerspine', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dalaran', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Dalvengyr', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dark Iron', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Darkspear', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Darrowmere', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dath''Remar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Dawnbringer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Deathwing', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Demon Soul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dentarg', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Destromath', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dethecus', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Detheroc', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Doomhammer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Draenor', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Dragonblight', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Dragonmaw', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Drak''Tharon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Drak''thul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Draka', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Drakkari', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Dreadmaul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Drenden', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Dunemaul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Durotan', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Duskwood', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Earthen Ring', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Echo Isles', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Eitrigg', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Eldre''Thalas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Elune', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Emerald Dream', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Eonar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Eredar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Executus', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Exodar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Farstriders', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Feathermoon', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Fenris', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Firetree', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Fizzcrank', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Frostmane', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Frostmourne', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Frostwolf', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Galakrond', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Garithos', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Garona', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Garrosh', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Ghostlands', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Gilneas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Gnomeregan', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Gorefiend', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Gorgonnash', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Greymane', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Grizzly Hills', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Gul''dan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Gundrak', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Gurubashi', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Hakkar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Haomarush', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Hellscream', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Hydraxis', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Hyjal', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Icecrown', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Illidan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Jaedenar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Jubei''Thos', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Kael''thas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Kalecgos', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Kargath', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Kel''Thuzad', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Khadgar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Khaz Modan', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Khaz''goroth', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Kil''Jaeden', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Kilrogg', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Kirin Tor', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Korgath', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Korialstrasz', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Kul Tiras', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Laughing Skull', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Lethon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Lightbringer', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Lightning''s Blade', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Lightninghoof', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Llane', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Lothar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Madoran', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Maelstrom', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Magtheridon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Maiev', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Mal''Ganis', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Malfurion', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Malorne', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Malygos', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Mannoroth', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Medivh', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Misha', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Mok''Nathal', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Moon Guard', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Moonrunner', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Mug''thol', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Muradin', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Nagrand', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Nathrezim', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Nazgrel', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Nazjatar', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Ner''zhul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Nordrassil', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Norgannon', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Onyxia', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Perenolde', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Proudmoore', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Quel''dorei', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Quel''Thalas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Ragnaros', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Ravencrest', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Ravenholdt', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Rexxar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Rivendare', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Runetotem', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Sargeras', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Saurfang', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Scarlet Crusade', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Scilla', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Sen''Jin', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Sentinels', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Shadow Council', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Shadowmoon', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Shadowsong', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Shandris', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Shattered Halls', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Shattered Hand', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Shu''halo', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Silver Hand', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Silvermoon', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Sisters of Elune', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Skullcrusher', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Skywall', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Smolderthorn', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Spinebreaker', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Spirestone', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Staghelm', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Steamwheedle Cartel', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Stonemaul', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Stormrage', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Stormreaver', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Stormscale', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Suramar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Tanaris', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Terenas', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Terokkar', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Thaurissan', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'The Forgotten Coast', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'The Scryers', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'The Underbog', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'The Venture Co', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Thorium Brotherhood', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Thrall', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Thunderhorn', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Thunderlord', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Tichondrius', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Tortheldrin', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Trollbane', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Turalyon', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Twisting Nether', 'English', 'RP-PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Uldaman', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Uldum', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Undermine', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Ursin', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Uther', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Vashj', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Vek''nilash', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Velen', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Warsong', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Whisperwind', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'WildHammer', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Windrunner', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Winterhoof', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Wyrmrest Accord', 'English', 'RP');
insert into cprRealm (region, name, language, type) values ('US', 'Ysera', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Ysondre', 'English', 'PvP');
insert into cprRealm (region, name, language, type) values ('US', 'Zangarmarsh', 'English', 'Normal');
insert into cprRealm (region, name, language, type) values ('US', 'Zul''jin', 'English', 'Normal');


