/*
 * colors.h
 *
 * Copyright (C) 2008 - 2011 by Joshua S. English. This document is the
 * intellectual property of Joshua S. English, all rights reserved.
 *
 * The set of RGBA colors for the Asgard Game Engine based upon the set of
 * common HTML color codes, along with color-related data types and helper
 * functions, header file.
 *
 * Written by Josh English.
 */

#if !defined(_ASGARD_CORE_COLORS_H)

#define _ASGARD_CORE_COLORS_H

#if !defined(_ASGARD_H) && !defined(_ASGARD_CORE_COMPONENT)
#	error "Incorrect use of this header file."
#endif // _ASGARD_H || _ASGARD_CORE_COMPONENT

#if defined(__cplusplus)
extern "C" {
#endif // __cplusplus


// define colors public data types

typedef struct _Color {
	double r;
	double g;
	double b;
	double a;
} Color;


// declare colors public functions

Color *colors_new();

Color *colors_newByName(char *colorName);

Color *colors_clone(Color *color);

Color *colors_load(Log *log, char *assetFilename);

void colors_free(Color *color);

void colors_getColor(char *colorName, Color *color);


// define colors public constants

// define RGBA color codes

// red colors

#define CGI_COLOR_INDIANRED_NAME					"IndianRed"
#define CGI_COLOR_INDIANRED_RED						0.800781
#define CGI_COLOR_INDIANRED_GREEN					0.359375
#define CGI_COLOR_INDIANRED_BLUE					0.359375
#define CGI_COLOR_INDIANRED_ALPHA					1.000000

#define CGI_COLOR_LIGHTCORAL_NAME					"LightCoral"
#define CGI_COLOR_LIGHTCORAL_RED					0.937500
#define CGI_COLOR_LIGHTCORAL_GREEN					0.500000
#define CGI_COLOR_LIGHTCORAL_BLUE					0.500000
#define CGI_COLOR_LIGHTCORAL_ALPHA					1.000000

#define CGI_COLOR_SALMON_NAME						"Salmon"
#define CGI_COLOR_SALMON_RED						0.976562
#define CGI_COLOR_SALMON_GREEN						0.500000
#define CGI_COLOR_SALMON_BLUE						0.445312
#define CGI_COLOR_SALMON_ALPHA						1.000000

#define CGI_COLOR_DARKSALMON_NAME					"DarkSalmon"
#define CGI_COLOR_DARKSALMON_RED					0.910156
#define CGI_COLOR_DARKSALMON_GREEN					0.585938
#define CGI_COLOR_DARKSALMON_BLUE					0.476562
#define CGI_COLOR_DARKSALMON_ALPHA					1.000000

#define CGI_COLOR_LIGHTSALMON_NAME					"LightSalmon"
#define CGI_COLOR_LIGHTSALMON_RED					0.996094
#define CGI_COLOR_LIGHTSALMON_GREEN					0.625000
#define CGI_COLOR_LIGHTSALMON_BLUE					0.476562
#define CGI_COLOR_LIGHTSALMON_ALPHA					1.000000

#define CGI_COLOR_CRIMSON_NAME						"Crimson"
#define CGI_COLOR_CRIMSON_RED						0.859375
#define CGI_COLOR_CRIMSON_GREEN						0.078125
#define CGI_COLOR_CRIMSON_BLUE						0.234375
#define CGI_COLOR_CRIMSON_ALPHA						1.000000

#define CGI_COLOR_RED_NAME							"Red"
#define CGI_COLOR_RED_RED							0.996094
#define CGI_COLOR_RED_GREEN							0.000000
#define CGI_COLOR_RED_BLUE							0.000000
#define CGI_COLOR_RED_ALPHA							1.000000

#define CGI_COLOR_FIREBRICK_NAME					"FireBrick"
#define CGI_COLOR_FIREBRICK_RED						0.695312
#define CGI_COLOR_FIREBRICK_GREEN					0.132812
#define CGI_COLOR_FIREBRICK_BLUE					0.132812
#define CGI_COLOR_FIREBRICK_ALPHA					1.000000

#define CGI_COLOR_DARKRED_NAME						"DarkRed"
#define CGI_COLOR_DARKRED_RED						0.542969
#define CGI_COLOR_DARKRED_GREEN						0.000000
#define CGI_COLOR_DARKRED_BLUE						0.000000
#define CGI_COLOR_DARKRED_ALPHA						1.000000

// pink colors

#define CGI_COLOR_PINK_NAME							"Pink"
#define CGI_COLOR_PINK_RED							0.996094
#define CGI_COLOR_PINK_GREEN						0.750000
#define CGI_COLOR_PINK_BLUE							0.792969
#define CGI_COLOR_PINK_ALPHA						1.000000

#define CGI_COLOR_LIGHTPINK_NAME					"LightPink"
#define CGI_COLOR_LIGHTPINK_RED						0.996094
#define CGI_COLOR_LIGHTPINK_GREEN					0.710938
#define CGI_COLOR_LIGHTPINK_BLUE					0.753906
#define CGI_COLOR_LIGHTPINK_ALPHA					1.000000

#define CGI_COLOR_HOTPINK_NAME						"HotPink"
#define CGI_COLOR_HOTPINK_RED						0.996094
#define CGI_COLOR_HOTPINK_GREEN						0.410156
#define CGI_COLOR_HOTPINK_BLUE						0.703125
#define CGI_COLOR_HOTPINK_ALPHA						1.000000

#define CGI_COLOR_DEEPPINK_NAME						"DeepPink"
#define CGI_COLOR_DEEPPINK_RED						0.996094
#define CGI_COLOR_DEEPPINK_GREEN					0.078125
#define CGI_COLOR_DEEPPINK_BLUE						0.574219
#define CGI_COLOR_DEEPPINK_ALPHA					1.000000

#define CGI_COLOR_MEDIUMVIOLETRED_NAME				"MediumVioletRed"
#define CGI_COLOR_MEDIUMVIOLETRED_RED				0.777344
#define CGI_COLOR_MEDIUMVIOLETRED_GREEN				0.082031
#define CGI_COLOR_MEDIUMVIOLETRED_BLUE				0.519531
#define CGI_COLOR_MEDIUMVIOLETRED_ALPHA				1.000000

#define CGI_COLOR_PALEVIOLETRED_NAME				"PaleVioletRed"
#define CGI_COLOR_PALEVIOLETRED_RED					0.855469
#define CGI_COLOR_PALEVIOLETRED_GREEN				0.437500
#define CGI_COLOR_PALEVIOLETRED_BLUE				0.574219
#define CGI_COLOR_PALEVIOLETRED_ALPHA				1.000000

// orange colors

#define CGI_COLOR_LIGHTSALMON_NAME					"LightSalmon"
#define CGI_COLOR_LIGHTSALMON_RED					0.996094
#define CGI_COLOR_LIGHTSALMON_GREEN					0.625000
#define CGI_COLOR_LIGHTSALMON_BLUE					0.476562
#define CGI_COLOR_LIGHTSALMON_ALPHA					1.000000

#define CGI_COLOR_CORAL_NAME						"Coral"
#define CGI_COLOR_CORAL_RED							0.996094
#define CGI_COLOR_CORAL_GREEN						0.496094
#define CGI_COLOR_CORAL_BLUE						0.312500
#define CGI_COLOR_CORAL_ALPHA						1.000000

#define CGI_COLOR_TOMATO_NAME						"Tomato"
#define CGI_COLOR_TOMATO_RED						0.996094
#define CGI_COLOR_TOMATO_GREEN						0.386719
#define CGI_COLOR_TOMATO_BLUE						0.277344
#define CGI_COLOR_TOMATO_ALPHA						1.000000

#define CGI_COLOR_ORANGERED_NAME					"OrangeRed"
#define CGI_COLOR_ORANGERED_RED						0.996094
#define CGI_COLOR_ORANGERED_GREEN					0.269531
#define CGI_COLOR_ORANGERED_BLUE					0.000000
#define CGI_COLOR_ORANGERED_ALPHA					1.000000

#define CGI_COLOR_DARKORANGE_NAME					"DarkOrange"
#define CGI_COLOR_DARKORANGE_RED					0.996094
#define CGI_COLOR_DARKORANGE_GREEN					0.546875
#define CGI_COLOR_DARKORANGE_BLUE					0.000000
#define CGI_COLOR_DARKORANGE_ALPHA					1.000000

#define CGI_COLOR_ORANGE_NAME						"Orange"
#define CGI_COLOR_ORANGE_RED						0.996094
#define CGI_COLOR_ORANGE_GREEN						0.644531
#define CGI_COLOR_ORANGE_BLUE						0.000000
#define CGI_COLOR_ORANGE_ALPHA						1.000000

// yellow colors

#define CGI_COLOR_GOLD_NAME							"Gold"
#define CGI_COLOR_GOLD_RED							0.996094
#define CGI_COLOR_GOLD_GREEN						0.839844
#define CGI_COLOR_GOLD_BLUE							0.000000
#define CGI_COLOR_GOLD_ALPHA						1.000000

#define CGI_COLOR_YELLOW_NAME						"Yellow"
#define CGI_COLOR_YELLOW_RED						0.996094
#define CGI_COLOR_YELLOW_GREEN						0.996094
#define CGI_COLOR_YELLOW_BLUE						0.000000
#define CGI_COLOR_YELLOW_ALPHA						1.000000

#define CGI_COLOR_LIGHTYELLOW_NAME					"LightYellow"
#define CGI_COLOR_LIGHTYELLOW_RED					0.996094
#define CGI_COLOR_LIGHTYELLOW_GREEN					0.996094
#define CGI_COLOR_LIGHTYELLOW_BLUE					0.875000
#define CGI_COLOR_LIGHTYELLOW_ALPHA					1.000000

#define CGI_COLOR_LEMONCHIFFON_NAME					"LemonChiffon"
#define CGI_COLOR_LEMONCHIFFON_RED					0.996094
#define CGI_COLOR_LEMONCHIFFON_GREEN				0.976562
#define CGI_COLOR_LEMONCHIFFON_BLUE					0.800781
#define CGI_COLOR_LEMONCHIFFON_ALPHA				1.000000

#define CGI_COLOR_LIGHTGOLDENRODYELLOW_NAME			"LightGoldenrodYellow"
#define CGI_COLOR_LIGHTGOLDENRODYELLOW_RED			0.976562
#define CGI_COLOR_LIGHTGOLDENRODYELLOW_GREEN		0.976562
#define CGI_COLOR_LIGHTGOLDENRODYELLOW_BLUE			0.820312
#define CGI_COLOR_LIGHTGOLDENRODYELLOW_ALPHA		1.000000

#define CGI_COLOR_PAPAYAWHIP_NAME					"PapayaWhip"
#define CGI_COLOR_PAPAYAWHIP_RED					0.996094
#define CGI_COLOR_PAPAYAWHIP_GREEN					0.933594
#define CGI_COLOR_PAPAYAWHIP_BLUE					0.832031
#define CGI_COLOR_PAPAYAWHIP_ALPHA					1.000000

#define CGI_COLOR_MOCCASIN_NAME						"Moccasin"
#define CGI_COLOR_MOCCASIN_RED						0.996094
#define CGI_COLOR_MOCCASIN_GREEN					0.890625
#define CGI_COLOR_MOCCASIN_BLUE						0.707031
#define CGI_COLOR_MOCCASIN_ALPHA					1.000000

#define CGI_COLOR_PEACHPUFF_NAME					"PeachPuff"
#define CGI_COLOR_PEACHPUFF_RED						0.996094
#define CGI_COLOR_PEACHPUFF_GREEN					0.851562
#define CGI_COLOR_PEACHPUFF_BLUE					0.722656
#define CGI_COLOR_PEACHPUFF_ALPHA					1.000000

#define CGI_COLOR_PALEGOLDENROD_NAME				"PaleGoldenrod"
#define CGI_COLOR_PALEGOLDENROD_RED					0.929688
#define CGI_COLOR_PALEGOLDENROD_GREEN				0.906250
#define CGI_COLOR_PALEGOLDENROD_BLUE				0.664062
#define CGI_COLOR_PALEGOLDENROD_ALPHA				1.000000

#define CGI_COLOR_KHAKI_NAME						"Khaki"
#define CGI_COLOR_KHAKI_RED							0.937500
#define CGI_COLOR_KHAKI_GREEN						0.898438
#define CGI_COLOR_KHAKI_BLUE						0.546875
#define CGI_COLOR_KHAKI_ALPHA						1.000000

#define CGI_COLOR_DARKKHAKI_NAME					"DarkKhaki"
#define CGI_COLOR_DARKKHAKI_RED						0.738281
#define CGI_COLOR_DARKKHAKI_GREEN					0.714844
#define CGI_COLOR_DARKKHAKI_BLUE					0.417969
#define CGI_COLOR_DARKKHAKI_ALPHA					1.000000

// purple colors

#define CGI_COLOR_LAVENDER_NAME						"Lavender"
#define CGI_COLOR_LAVENDER_RED						0.898438
#define CGI_COLOR_LAVENDER_GREEN					0.898438
#define CGI_COLOR_LAVENDER_BLUE						0.976562
#define CGI_COLOR_LAVENDER_ALPHA					1.000000

#define CGI_COLOR_THISTLE_NAME						"Thistle"
#define CGI_COLOR_THISTLE_RED						0.843750
#define CGI_COLOR_THISTLE_GREEN						0.746094
#define CGI_COLOR_THISTLE_BLUE						0.843750
#define CGI_COLOR_THISTLE_ALPHA						1.000000

#define CGI_COLOR_PLUM_NAME							"Plum"
#define CGI_COLOR_PLUM_RED							0.863281
#define CGI_COLOR_PLUM_GREEN						0.625000
#define CGI_COLOR_PLUM_BLUE							0.863281
#define CGI_COLOR_PLUM_ALPHA						1.000000

#define CGI_COLOR_VIOLET_NAME						"Violet"
#define CGI_COLOR_VIOLET_RED						0.929688
#define CGI_COLOR_VIOLET_GREEN						0.507812
#define CGI_COLOR_VIOLET_BLUE						0.929688
#define CGI_COLOR_VIOLET_ALPHA						1.000000

#define CGI_COLOR_ORCHID_NAME						"Orchid"
#define CGI_COLOR_ORCHID_RED						0.851562
#define CGI_COLOR_ORCHID_GREEN						0.437500
#define CGI_COLOR_ORCHID_BLUE						0.835938
#define CGI_COLOR_ORCHID_ALPHA						1.000000

#define CGI_COLOR_FUCHSIA_NAME						"Fuchsia"
#define CGI_COLOR_FUCHSIA_RED						0.996094
#define CGI_COLOR_FUCHSIA_GREEN						0.000000
#define CGI_COLOR_FUCHSIA_BLUE						0.996094
#define CGI_COLOR_FUCHSIA_ALPHA						1.000000

#define CGI_COLOR_MAGENTA_NAME						"Magenta"
#define CGI_COLOR_MAGENTA_RED						0.996094
#define CGI_COLOR_MAGENTA_GREEN						0.000000
#define CGI_COLOR_MAGENTA_BLUE						0.996094
#define CGI_COLOR_MAGENTA_ALPHA						1.000000

#define CGI_COLOR_MEDIUMORCHID_NAME					"MediumOrchid"
#define CGI_COLOR_MEDIUMORCHID_RED					0.726562
#define CGI_COLOR_MEDIUMORCHID_GREEN				0.332031
#define CGI_COLOR_MEDIUMORCHID_BLUE					0.824219
#define CGI_COLOR_MEDIUMORCHID_ALPHA				1.000000

#define CGI_COLOR_MEDIUMPURPLE_NAME					"MediumPurple"
#define CGI_COLOR_MEDIUMPURPLE_RED					0.574219
#define CGI_COLOR_MEDIUMPURPLE_GREEN				0.437500
#define CGI_COLOR_MEDIUMPURPLE_BLUE					0.855469
#define CGI_COLOR_MEDIUMPURPLE_ALPHA				1.000000

#define CGI_COLOR_AMETHYST_NAME						"Amethyst"
#define CGI_COLOR_AMETHYST_RED						0.597656
#define CGI_COLOR_AMETHYST_GREEN					0.398438
#define CGI_COLOR_AMETHYST_BLUE						0.796875
#define CGI_COLOR_AMETHYST_ALPHA					1.000000

#define CGI_COLOR_BLUEVIOLET_NAME					"BlueViolet"
#define CGI_COLOR_BLUEVIOLET_RED					0.539062
#define CGI_COLOR_BLUEVIOLET_GREEN					0.167969
#define CGI_COLOR_BLUEVIOLET_BLUE					0.882812
#define CGI_COLOR_BLUEVIOLET_ALPHA					1.000000

#define CGI_COLOR_DARKVIOLET_NAME					"DarkViolet"
#define CGI_COLOR_DARKVIOLET_RED					0.578125
#define CGI_COLOR_DARKVIOLET_GREEN					0.000000
#define CGI_COLOR_DARKVIOLET_BLUE					0.824219
#define CGI_COLOR_DARKVIOLET_ALPHA					1.000000

#define CGI_COLOR_DARKORCHID_NAME					"DarkOrchid"
#define CGI_COLOR_DARKORCHID_RED					0.597656
#define CGI_COLOR_DARKORCHID_GREEN					0.195312
#define CGI_COLOR_DARKORCHID_BLUE					0.796875
#define CGI_COLOR_DARKORCHID_ALPHA					1.000000

#define CGI_COLOR_DARKMAGENTA_NAME					"DarkMagenta"
#define CGI_COLOR_DARKMAGENTA_RED					0.542969
#define CGI_COLOR_DARKMAGENTA_GREEN					0.000000
#define CGI_COLOR_DARKMAGENTA_BLUE					0.542969
#define CGI_COLOR_DARKMAGENTA_ALPHA					1.000000

#define CGI_COLOR_PURPLE_NAME						"Purple"
#define CGI_COLOR_PURPLE_RED						0.500000
#define CGI_COLOR_PURPLE_GREEN						0.000000
#define CGI_COLOR_PURPLE_BLUE						0.500000
#define CGI_COLOR_PURPLE_ALPHA						1.000000

#define CGI_COLOR_INDIGO_NAME						"Indigo"
#define CGI_COLOR_INDIGO_RED						0.292969
#define CGI_COLOR_INDIGO_GREEN						0.000000
#define CGI_COLOR_INDIGO_BLUE						0.507812
#define CGI_COLOR_INDIGO_ALPHA						1.000000

#define CGI_COLOR_SLATEBLUE_NAME					"SlateBlue"
#define CGI_COLOR_SLATEBLUE_RED						0.414062
#define CGI_COLOR_SLATEBLUE_GREEN					0.351562
#define CGI_COLOR_SLATEBLUE_BLUE					0.800781
#define CGI_COLOR_SLATEBLUE_ALPHA					1.000000

#define CGI_COLOR_DARKSLATEBLUE_NAME				"DarkSlateBlue"
#define CGI_COLOR_DARKSLATEBLUE_RED					0.281250
#define CGI_COLOR_DARKSLATEBLUE_GREEN				0.238281
#define CGI_COLOR_DARKSLATEBLUE_BLUE				0.542969
#define CGI_COLOR_DARKSLATEBLUE_ALPHA				1.000000

#define CGI_COLOR_MEDIUMSLATEBLUE_NAME				"MediumSlateBlue"
#define CGI_COLOR_MEDIUMSLATEBLUE_RED				0.480469
#define CGI_COLOR_MEDIUMSLATEBLUE_GREEN				0.406250
#define CGI_COLOR_MEDIUMSLATEBLUE_BLUE				0.929688
#define CGI_COLOR_MEDIUMSLATEBLUE_ALPHA				1.000000

// green colors

#define CGI_COLOR_GREENYELLOW_NAME					"GreenYellow"
#define CGI_COLOR_GREENYELLOW_RED					0.675781
#define CGI_COLOR_GREENYELLOW_GREEN					0.996094
#define CGI_COLOR_GREENYELLOW_BLUE					0.183594
#define CGI_COLOR_GREENYELLOW_ALPHA					1.000000

#define CGI_COLOR_CHARTREUSE_NAME					"Chartreuse"
#define CGI_COLOR_CHARTREUSE_RED					0.496094
#define CGI_COLOR_CHARTREUSE_GREEN					0.996094
#define CGI_COLOR_CHARTREUSE_BLUE					0.000000
#define CGI_COLOR_CHARTREUSE_ALPHA					1.000000

#define CGI_COLOR_LAWNGREEN_NAME					"LawnGreen"
#define CGI_COLOR_LAWNGREEN_RED						0.484375
#define CGI_COLOR_LAWNGREEN_GREEN					0.984375
#define CGI_COLOR_LAWNGREEN_BLUE					0.000000
#define CGI_COLOR_LAWNGREEN_ALPHA					1.000000

#define CGI_COLOR_LIME_NAME							"Lime"
#define CGI_COLOR_LIME_RED							0.000000
#define CGI_COLOR_LIME_GREEN						0.996094
#define CGI_COLOR_LIME_BLUE							0.000000
#define CGI_COLOR_LIME_ALPHA						1.000000

#define CGI_COLOR_LIMEGREEN_NAME					"LimeGreen"
#define CGI_COLOR_LIMEGREEN_RED						0.195312
#define CGI_COLOR_LIMEGREEN_GREEN					0.800781
#define CGI_COLOR_LIMEGREEN_BLUE					0.195312
#define CGI_COLOR_LIMEGREEN_ALPHA					1.000000

#define CGI_COLOR_PALEGREEN_NAME					"PaleGreen"
#define CGI_COLOR_PALEGREEN_RED						0.593750
#define CGI_COLOR_PALEGREEN_GREEN					0.980469
#define CGI_COLOR_PALEGREEN_BLUE					0.593750
#define CGI_COLOR_PALEGREEN_ALPHA					1.000000

#define CGI_COLOR_LIGHTGREEN_NAME					"LightGreen"
#define CGI_COLOR_LIGHTGREEN_RED					0.562500
#define CGI_COLOR_LIGHTGREEN_GREEN					0.929688
#define CGI_COLOR_LIGHTGREEN_BLUE					0.562500
#define CGI_COLOR_LIGHTGREEN_ALPHA					1.000000

#define CGI_COLOR_MEDIUMSPRINGGREEN_NAME			"MediumSpringGreen"
#define CGI_COLOR_MEDIUMSPRINGGREEN_RED				0.000000
#define CGI_COLOR_MEDIUMSPRINGGREEN_GREEN			0.976562
#define CGI_COLOR_MEDIUMSPRINGGREEN_BLUE			0.601562
#define CGI_COLOR_MEDIUMSPRINGGREEN_ALPHA			1.000000

#define CGI_COLOR_SPRINGGREEN_NAME					"SpringGreen"
#define CGI_COLOR_SPRINGGREEN_RED					0.000000
#define CGI_COLOR_SPRINGGREEN_GREEN					0.996094
#define CGI_COLOR_SPRINGGREEN_BLUE					0.496094
#define CGI_COLOR_SPRINGGREEN_ALPHA					1.000000

#define CGI_COLOR_MEDIUMSEAGREEN_NAME				"MediumSeaGreen"
#define CGI_COLOR_MEDIUMSEAGREEN_RED				0.234375
#define CGI_COLOR_MEDIUMSEAGREEN_GREEN				0.699219
#define CGI_COLOR_MEDIUMSEAGREEN_BLUE				0.441406
#define CGI_COLOR_MEDIUMSEAGREEN_ALPHA				1.000000

#define CGI_COLOR_SEAGREEN_NAME						"SeaGreen"
#define CGI_COLOR_SEAGREEN_RED						0.179688
#define CGI_COLOR_SEAGREEN_GREEN					0.542969
#define CGI_COLOR_SEAGREEN_BLUE						0.339844
#define CGI_COLOR_SEAGREEN_ALPHA					1.000000

#define CGI_COLOR_FORESTGREEN_NAME					"ForestGreen"
#define CGI_COLOR_FORESTGREEN_RED					0.132812
#define CGI_COLOR_FORESTGREEN_GREEN					0.542969
#define CGI_COLOR_FORESTGREEN_BLUE					0.132812
#define CGI_COLOR_FORESTGREEN_ALPHA					1.000000

#define CGI_COLOR_GREEN_NAME						"Green"
#define CGI_COLOR_GREEN_RED							0.000000
#define CGI_COLOR_GREEN_GREEN						0.500000
#define CGI_COLOR_GREEN_BLUE						0.000000
#define CGI_COLOR_GREEN_ALPHA						1.000000

#define CGI_COLOR_DARKGREEN_NAME					"DarkGreen"
#define CGI_COLOR_DARKGREEN_RED						0.000000
#define CGI_COLOR_DARKGREEN_GREEN					0.390625
#define CGI_COLOR_DARKGREEN_BLUE					0.000000
#define CGI_COLOR_DARKGREEN_ALPHA					1.000000

#define CGI_COLOR_YELLOWGREEN_NAME					"YellowGreen"
#define CGI_COLOR_YELLOWGREEN_RED					0.601562
#define CGI_COLOR_YELLOWGREEN_GREEN					0.800781
#define CGI_COLOR_YELLOWGREEN_BLUE					0.195312
#define CGI_COLOR_YELLOWGREEN_ALPHA					1.000000

#define CGI_COLOR_OLIVEDRAB_NAME					"OliveDrab"
#define CGI_COLOR_OLIVEDRAB_RED						0.417969
#define CGI_COLOR_OLIVEDRAB_GREEN					0.554688
#define CGI_COLOR_OLIVEDRAB_BLUE					0.136719
#define CGI_COLOR_OLIVEDRAB_ALPHA					1.000000

#define CGI_COLOR_OLIVE_NAME						"Olive"
#define CGI_COLOR_OLIVE_RED							0.500000
#define CGI_COLOR_OLIVE_GREEN						0.500000
#define CGI_COLOR_OLIVE_BLUE						0.000000
#define CGI_COLOR_OLIVE_ALPHA						1.000000

#define CGI_COLOR_DARKOLIVEGREEN_NAME				"DarkOliveGreen"
#define CGI_COLOR_DARKOLIVEGREEN_RED				0.332031
#define CGI_COLOR_DARKOLIVEGREEN_GREEN				0.417969
#define CGI_COLOR_DARKOLIVEGREEN_BLUE				0.183594
#define CGI_COLOR_DARKOLIVEGREEN_ALPHA				1.000000

#define CGI_COLOR_MEDIUMAQUAMARINE_NAME				"MediumAquamarine"
#define CGI_COLOR_MEDIUMAQUAMARINE_RED				0.398438
#define CGI_COLOR_MEDIUMAQUAMARINE_GREEN			0.800781
#define CGI_COLOR_MEDIUMAQUAMARINE_BLUE				0.664062
#define CGI_COLOR_MEDIUMAQUAMARINE_ALPHA			1.000000

#define CGI_COLOR_DARKSEAGREEN_NAME					"DarkSeaGreen"
#define CGI_COLOR_DARKSEAGREEN_RED					0.558594
#define CGI_COLOR_DARKSEAGREEN_GREEN				0.734375
#define CGI_COLOR_DARKSEAGREEN_BLUE					0.558594
#define CGI_COLOR_DARKSEAGREEN_ALPHA				1.000000

#define CGI_COLOR_LIGHTSEAGREEN_NAME				"LightSeaGreen"
#define CGI_COLOR_LIGHTSEAGREEN_RED					0.125000
#define CGI_COLOR_LIGHTSEAGREEN_GREEN				0.695312
#define CGI_COLOR_LIGHTSEAGREEN_BLUE				0.664062
#define CGI_COLOR_LIGHTSEAGREEN_ALPHA				1.000000

#define CGI_COLOR_DARKCYAN_NAME						"DarkCyan"
#define CGI_COLOR_DARKCYAN_RED						0.000000
#define CGI_COLOR_DARKCYAN_GREEN					0.542969
#define CGI_COLOR_DARKCYAN_BLUE						0.542969
#define CGI_COLOR_DARKCYAN_ALPHA					1.000000

#define CGI_COLOR_TEAL_NAME							"Teal"
#define CGI_COLOR_TEAL_RED							0.000000
#define CGI_COLOR_TEAL_GREEN						0.500000
#define CGI_COLOR_TEAL_BLUE							0.500000
#define CGI_COLOR_TEAL_ALPHA						1.000000

// blue colors

#define CGI_COLOR_AQUA_NAME							"Aqua"
#define CGI_COLOR_AQUA_RED							0.000000
#define CGI_COLOR_AQUA_GREEN						0.996094
#define CGI_COLOR_AQUA_BLUE							0.996094
#define CGI_COLOR_AQUA_ALPHA						1.000000

#define CGI_COLOR_CYAN_NAME							"Cyan"
#define CGI_COLOR_CYAN_RED							0.000000
#define CGI_COLOR_CYAN_GREEN						0.996094
#define CGI_COLOR_CYAN_BLUE							0.996094
#define CGI_COLOR_CYAN_ALPHA						1.000000

#define CGI_COLOR_LIGHTCYAN_NAME					"LightCyan"
#define CGI_COLOR_LIGHTCYAN_RED						0.875000
#define CGI_COLOR_LIGHTCYAN_GREEN					0.996094
#define CGI_COLOR_LIGHTCYAN_BLUE					0.996094
#define CGI_COLOR_LIGHTCYAN_ALPHA					1.000000

#define CGI_COLOR_PALETURQUOISE_NAME				"PaleTurquoise"
#define CGI_COLOR_PALETURQUOISE_RED					0.683594
#define CGI_COLOR_PALETURQUOISE_GREEN				0.929688
#define CGI_COLOR_PALETURQUOISE_BLUE				0.929688
#define CGI_COLOR_PALETURQUOISE_ALPHA				1.000000

#define CGI_COLOR_AQUAMARINE_NAME					"Aquamarine"
#define CGI_COLOR_AQUAMARINE_RED					0.496094
#define CGI_COLOR_AQUAMARINE_GREEN					0.996094
#define CGI_COLOR_AQUAMARINE_BLUE					0.828125
#define CGI_COLOR_AQUAMARINE_ALPHA					1.000000

#define CGI_COLOR_TURQUOISE_NAME					"Turquoise"
#define CGI_COLOR_TURQUOISE_RED						0.250000
#define CGI_COLOR_TURQUOISE_GREEN					0.875000
#define CGI_COLOR_TURQUOISE_BLUE					0.812500
#define CGI_COLOR_TURQUOISE_ALPHA					1.000000

#define CGI_COLOR_MEDIUMTURQUOISE_NAME				"MediumTurquoise"
#define CGI_COLOR_MEDIUMTURQUOISE_RED				0.281250
#define CGI_COLOR_MEDIUMTURQUOISE_GREEN				0.816406
#define CGI_COLOR_MEDIUMTURQUOISE_BLUE				0.796875
#define CGI_COLOR_MEDIUMTURQUOISE_ALPHA				1.000000

#define CGI_COLOR_DARKTURQUOISE_NAME				"DarkTurquoise"
#define CGI_COLOR_DARKTURQUOISE_RED					0.000000
#define CGI_COLOR_DARKTURQUOISE_GREEN				0.804688
#define CGI_COLOR_DARKTURQUOISE_BLUE				0.816406
#define CGI_COLOR_DARKTURQUOISE_ALPHA				1.000000

#define CGI_COLOR_CADETBLUE_NAME					"CadetBlue"
#define CGI_COLOR_CADETBLUE_RED						0.371094
#define CGI_COLOR_CADETBLUE_GREEN					0.617188
#define CGI_COLOR_CADETBLUE_BLUE					0.625000
#define CGI_COLOR_CADETBLUE_ALPHA					1.000000

#define CGI_COLOR_STEELBLUE_NAME					"SteelBlue"
#define CGI_COLOR_STEELBLUE_RED						0.273438
#define CGI_COLOR_STEELBLUE_GREEN					0.507812
#define CGI_COLOR_STEELBLUE_BLUE					0.703125
#define CGI_COLOR_STEELBLUE_ALPHA					1.000000

#define CGI_COLOR_LIGHTSTEELBLUE_NAME				"LightSteelBlue"
#define CGI_COLOR_LIGHTSTEELBLUE_RED				0.687500
#define CGI_COLOR_LIGHTSTEELBLUE_GREEN				0.765625
#define CGI_COLOR_LIGHTSTEELBLUE_BLUE				0.867188
#define CGI_COLOR_LIGHTSTEELBLUE_ALPHA				1.000000

#define CGI_COLOR_POWDERBLUE_NAME					"PowderBlue"
#define CGI_COLOR_POWDERBLUE_RED					0.687500
#define CGI_COLOR_POWDERBLUE_GREEN					0.875000
#define CGI_COLOR_POWDERBLUE_BLUE					0.898438
#define CGI_COLOR_POWDERBLUE_ALPHA					1.000000

#define CGI_COLOR_LIGHTBLUE_NAME					"LightBlue"
#define CGI_COLOR_LIGHTBLUE_RED						0.675781
#define CGI_COLOR_LIGHTBLUE_GREEN					0.843750
#define CGI_COLOR_LIGHTBLUE_BLUE					0.898438
#define CGI_COLOR_LIGHTBLUE_ALPHA					1.000000

#define CGI_COLOR_SKYBLUE_NAME						"SkyBlue"
#define CGI_COLOR_SKYBLUE_RED						0.527344
#define CGI_COLOR_SKYBLUE_GREEN						0.804688
#define CGI_COLOR_SKYBLUE_BLUE						0.917969
#define CGI_COLOR_SKYBLUE_ALPHA						1.000000

#define CGI_COLOR_LIGHTSKYBLUE_NAME					"LightSkyBlue"
#define CGI_COLOR_LIGHTSKYBLUE_RED					0.527344
#define CGI_COLOR_LIGHTSKYBLUE_GREEN				0.804688
#define CGI_COLOR_LIGHTSKYBLUE_BLUE					0.976562
#define CGI_COLOR_LIGHTSKYBLUE_ALPHA				1.000000

#define CGI_COLOR_DEEPSKYBLUE_NAME					"DeepSkyBlue"
#define CGI_COLOR_DEEPSKYBLUE_RED					0.000000
#define CGI_COLOR_DEEPSKYBLUE_GREEN					0.746094
#define CGI_COLOR_DEEPSKYBLUE_BLUE					0.996094
#define CGI_COLOR_DEEPSKYBLUE_ALPHA					1.000000

#define CGI_COLOR_DODGERBLUE_NAME					"DodgerBlue"
#define CGI_COLOR_DODGERBLUE_RED					0.117188
#define CGI_COLOR_DODGERBLUE_GREEN					0.562500
#define CGI_COLOR_DODGERBLUE_BLUE					0.996094
#define CGI_COLOR_DODGERBLUE_ALPHA					1.000000

#define CGI_COLOR_CORNFLOWERBLUE_NAME				"CornflowerBlue"
#define CGI_COLOR_CORNFLOWERBLUE_RED				0.390625
#define CGI_COLOR_CORNFLOWERBLUE_GREEN				0.582031
#define CGI_COLOR_CORNFLOWERBLUE_BLUE				0.925781
#define CGI_COLOR_CORNFLOWERBLUE_ALPHA				1.000000

#define CGI_COLOR_MEDIUMSLATEBLUE_NAME				"MediumSlateBlue"
#define CGI_COLOR_MEDIUMSLATEBLUE_RED				0.480469
#define CGI_COLOR_MEDIUMSLATEBLUE_GREEN				0.406250
#define CGI_COLOR_MEDIUMSLATEBLUE_BLUE				0.929688
#define CGI_COLOR_MEDIUMSLATEBLUE_ALPHA				1.000000

#define CGI_COLOR_ROYALBLUE_NAME					"RoyalBlue"
#define CGI_COLOR_ROYALBLUE_RED						0.253906
#define CGI_COLOR_ROYALBLUE_GREEN					0.410156
#define CGI_COLOR_ROYALBLUE_BLUE					0.878906
#define CGI_COLOR_ROYALBLUE_ALPHA					1.000000

#define CGI_COLOR_BLUE_NAME							"Blue"
#define CGI_COLOR_BLUE_RED							0.000000
#define CGI_COLOR_BLUE_GREEN						0.000000
#define CGI_COLOR_BLUE_BLUE							0.996094
#define CGI_COLOR_BLUE_ALPHA						1.000000

#define CGI_COLOR_MEDIUMBLUE_NAME					"MediumBlue"
#define CGI_COLOR_MEDIUMBLUE_RED					0.000000
#define CGI_COLOR_MEDIUMBLUE_GREEN					0.000000
#define CGI_COLOR_MEDIUMBLUE_BLUE					0.800781
#define CGI_COLOR_MEDIUMBLUE_ALPHA					1.000000

#define CGI_COLOR_DARKBLUE_NAME						"DarkBlue"
#define CGI_COLOR_DARKBLUE_RED						0.000000
#define CGI_COLOR_DARKBLUE_GREEN					0.000000
#define CGI_COLOR_DARKBLUE_BLUE						0.542969
#define CGI_COLOR_DARKBLUE_ALPHA					1.000000

#define CGI_COLOR_NAVY_NAME							"Navy"
#define CGI_COLOR_NAVY_RED							0.000000
#define CGI_COLOR_NAVY_GREEN						0.000000
#define CGI_COLOR_NAVY_BLUE							0.500000
#define CGI_COLOR_NAVY_ALPHA						1.000000

#define CGI_COLOR_MIDNIGHTBLUE_NAME					"MidnightBlue"
#define CGI_COLOR_MIDNIGHTBLUE_RED					0.097656
#define CGI_COLOR_MIDNIGHTBLUE_GREEN				0.097656
#define CGI_COLOR_MIDNIGHTBLUE_BLUE					0.437500
#define CGI_COLOR_MIDNIGHTBLUE_ALPHA				1.000000

// brown colors

#define CGI_COLOR_CORNSILK_NAME						"Cornsilk"
#define CGI_COLOR_CORNSILK_RED						0.996094
#define CGI_COLOR_CORNSILK_GREEN					0.968750
#define CGI_COLOR_CORNSILK_BLUE						0.859375
#define CGI_COLOR_CORNSILK_ALPHA					1.000000

#define CGI_COLOR_BLANCHEDALMOND_NAME				"BlanchedAlmond"
#define CGI_COLOR_BLANCHEDALMOND_RED				0.996094
#define CGI_COLOR_BLANCHEDALMOND_GREEN				0.917969
#define CGI_COLOR_BLANCHEDALMOND_BLUE				0.800781
#define CGI_COLOR_BLANCHEDALMOND_ALPHA				1.000000

#define CGI_COLOR_BISQUE_NAME						"Bisque"
#define CGI_COLOR_BISQUE_RED						0.996094
#define CGI_COLOR_BISQUE_GREEN						0.890625
#define CGI_COLOR_BISQUE_BLUE						0.765625
#define CGI_COLOR_BISQUE_ALPHA						1.000000

#define CGI_COLOR_NAVAJOWHITE_NAME					"NavajoWhite"
#define CGI_COLOR_NAVAJOWHITE_RED					0.996094
#define CGI_COLOR_NAVAJOWHITE_GREEN					0.867188
#define CGI_COLOR_NAVAJOWHITE_BLUE					0.675781
#define CGI_COLOR_NAVAJOWHITE_ALPHA					1.000000

#define CGI_COLOR_WHEAT_NAME						"Wheat"
#define CGI_COLOR_WHEAT_RED							0.957031
#define CGI_COLOR_WHEAT_GREEN						0.867188
#define CGI_COLOR_WHEAT_BLUE						0.699219
#define CGI_COLOR_WHEAT_ALPHA						1.000000

#define CGI_COLOR_BURLYWOOD_NAME					"BurlyWood"
#define CGI_COLOR_BURLYWOOD_RED						0.867188
#define CGI_COLOR_BURLYWOOD_GREEN					0.718750
#define CGI_COLOR_BURLYWOOD_BLUE					0.527344
#define CGI_COLOR_BURLYWOOD_ALPHA					1.000000

#define CGI_COLOR_TAN_NAME							"Tan"
#define CGI_COLOR_TAN_RED							0.820312
#define CGI_COLOR_TAN_GREEN							0.703125
#define CGI_COLOR_TAN_BLUE							0.546875
#define CGI_COLOR_TAN_ALPHA							1.000000

#define CGI_COLOR_ROSYBROWN_NAME					"RosyBrown"
#define CGI_COLOR_ROSYBROWN_RED						0.734375
#define CGI_COLOR_ROSYBROWN_GREEN					0.558594
#define CGI_COLOR_ROSYBROWN_BLUE					0.558594
#define CGI_COLOR_ROSYBROWN_ALPHA					1.000000

#define CGI_COLOR_SANDYBROWN_NAME					"SandyBrown"
#define CGI_COLOR_SANDYBROWN_RED					0.953125
#define CGI_COLOR_SANDYBROWN_GREEN					0.640625
#define CGI_COLOR_SANDYBROWN_BLUE					0.375000
#define CGI_COLOR_SANDYBROWN_ALPHA					1.000000

#define CGI_COLOR_GOLDENROD_NAME					"Goldenrod"
#define CGI_COLOR_GOLDENROD_RED						0.851562
#define CGI_COLOR_GOLDENROD_GREEN					0.644531
#define CGI_COLOR_GOLDENROD_BLUE					0.125000
#define CGI_COLOR_GOLDENROD_ALPHA					1.000000

#define CGI_COLOR_DARKGOLDENROD_NAME				"DarkGoldenrod"
#define CGI_COLOR_DARKGOLDENROD_RED					0.718750
#define CGI_COLOR_DARKGOLDENROD_GREEN				0.523438
#define CGI_COLOR_DARKGOLDENROD_BLUE				0.042969
#define CGI_COLOR_DARKGOLDENROD_ALPHA				1.000000

#define CGI_COLOR_PERU_NAME							"Peru"
#define CGI_COLOR_PERU_RED							0.800781
#define CGI_COLOR_PERU_GREEN						0.519531
#define CGI_COLOR_PERU_BLUE							0.246094
#define CGI_COLOR_PERU_ALPHA						1.000000

#define CGI_COLOR_CHOCOLATE_NAME					"Chocolate"
#define CGI_COLOR_CHOCOLATE_RED						0.820312
#define CGI_COLOR_CHOCOLATE_GREEN					0.410156
#define CGI_COLOR_CHOCOLATE_BLUE					0.117188
#define CGI_COLOR_CHOCOLATE_ALPHA					1.000000

#define CGI_COLOR_SADDLEBROWN_NAME					"SaddleBrown"
#define CGI_COLOR_SADDLEBROWN_RED					0.542969
#define CGI_COLOR_SADDLEBROWN_GREEN					0.269531
#define CGI_COLOR_SADDLEBROWN_BLUE					0.074219
#define CGI_COLOR_SADDLEBROWN_ALPHA					1.000000

#define CGI_COLOR_SIENNA_NAME						"Sienna"
#define CGI_COLOR_SIENNA_RED						0.625000
#define CGI_COLOR_SIENNA_GREEN						0.320312
#define CGI_COLOR_SIENNA_BLUE						0.175781
#define CGI_COLOR_SIENNA_ALPHA						1.000000

#define CGI_COLOR_BROWN_NAME						"Brown"
#define CGI_COLOR_BROWN_RED							0.644531
#define CGI_COLOR_BROWN_GREEN						0.164062
#define CGI_COLOR_BROWN_BLUE						0.164062
#define CGI_COLOR_BROWN_ALPHA						1.000000

#define CGI_COLOR_MAROON_NAME						"Maroon"
#define CGI_COLOR_MAROON_RED						0.500000
#define CGI_COLOR_MAROON_GREEN						0.000000
#define CGI_COLOR_MAROON_BLUE						0.000000
#define CGI_COLOR_MAROON_ALPHA						1.000000

// white colors

#define CGI_COLOR_WHITE_NAME						"White"
#define CGI_COLOR_WHITE_RED							0.996094
#define CGI_COLOR_WHITE_GREEN						0.996094
#define CGI_COLOR_WHITE_BLUE						0.996094
#define CGI_COLOR_WHITE_ALPHA						1.000000

#define CGI_COLOR_SNOW_NAME							"Snow"
#define CGI_COLOR_SNOW_RED							0.996094
#define CGI_COLOR_SNOW_GREEN						0.976562
#define CGI_COLOR_SNOW_BLUE							0.976562
#define CGI_COLOR_SNOW_ALPHA						1.000000

#define CGI_COLOR_HONEYDEW_NAME						"Honeydew"
#define CGI_COLOR_HONEYDEW_RED						0.937500
#define CGI_COLOR_HONEYDEW_GREEN					0.996094
#define CGI_COLOR_HONEYDEW_BLUE						0.937500
#define CGI_COLOR_HONEYDEW_ALPHA					1.000000

#define CGI_COLOR_MINTCREAM_NAME					"MintCream"
#define CGI_COLOR_MINTCREAM_RED						0.957031
#define CGI_COLOR_MINTCREAM_GREEN					0.996094
#define CGI_COLOR_MINTCREAM_BLUE					0.976562
#define CGI_COLOR_MINTCREAM_ALPHA					1.000000

#define CGI_COLOR_AZURE_NAME						"Azure"
#define CGI_COLOR_AZURE_RED							0.937500
#define CGI_COLOR_AZURE_GREEN						0.996094
#define CGI_COLOR_AZURE_BLUE						0.996094
#define CGI_COLOR_AZURE_ALPHA						1.000000

#define CGI_COLOR_ALICEBLUE_NAME					"AliceBlue"
#define CGI_COLOR_ALICEBLUE_RED						0.937500
#define CGI_COLOR_ALICEBLUE_GREEN					0.968750
#define CGI_COLOR_ALICEBLUE_BLUE					0.996094
#define CGI_COLOR_ALICEBLUE_ALPHA					1.000000

#define CGI_COLOR_GHOSTWHITE_NAME					"GhostWhite"
#define CGI_COLOR_GHOSTWHITE_RED					0.968750
#define CGI_COLOR_GHOSTWHITE_GREEN					0.968750
#define CGI_COLOR_GHOSTWHITE_BLUE					0.996094
#define CGI_COLOR_GHOSTWHITE_ALPHA					1.000000

#define CGI_COLOR_WHITESMOKE_NAME					"WhiteSmoke"
#define CGI_COLOR_WHITESMOKE_RED					0.957031
#define CGI_COLOR_WHITESMOKE_GREEN					0.957031
#define CGI_COLOR_WHITESMOKE_BLUE					0.957031
#define CGI_COLOR_WHITESMOKE_ALPHA					1.000000

#define CGI_COLOR_SEASHELL_NAME						"Seashell"
#define CGI_COLOR_SEASHELL_RED						0.996094
#define CGI_COLOR_SEASHELL_GREEN					0.957031
#define CGI_COLOR_SEASHELL_BLUE						0.929688
#define CGI_COLOR_SEASHELL_ALPHA					1.000000

#define CGI_COLOR_BEIGE_NAME						"Beige"
#define CGI_COLOR_BEIGE_RED							0.957031
#define CGI_COLOR_BEIGE_GREEN						0.957031
#define CGI_COLOR_BEIGE_BLUE						0.859375
#define CGI_COLOR_BEIGE_ALPHA						1.000000

#define CGI_COLOR_OLDLACE_NAME						"OldLace"
#define CGI_COLOR_OLDLACE_RED						0.988281
#define CGI_COLOR_OLDLACE_GREEN						0.957031
#define CGI_COLOR_OLDLACE_BLUE						0.898438
#define CGI_COLOR_OLDLACE_ALPHA						1.000000

#define CGI_COLOR_FLORALWHITE_NAME					"FloralWhite"
#define CGI_COLOR_FLORALWHITE_RED					0.996094
#define CGI_COLOR_FLORALWHITE_GREEN					0.976562
#define CGI_COLOR_FLORALWHITE_BLUE					0.937500
#define CGI_COLOR_FLORALWHITE_ALPHA					1.000000

#define CGI_COLOR_IVORY_NAME						"Ivory"
#define CGI_COLOR_IVORY_RED							0.996094
#define CGI_COLOR_IVORY_GREEN						0.996094
#define CGI_COLOR_IVORY_BLUE						0.937500
#define CGI_COLOR_IVORY_ALPHA						1.000000

#define CGI_COLOR_ANTIQUEWHITE_NAME					"AntiqueWhite"
#define CGI_COLOR_ANTIQUEWHITE_RED					0.976562
#define CGI_COLOR_ANTIQUEWHITE_GREEN				0.917969
#define CGI_COLOR_ANTIQUEWHITE_BLUE					0.839844
#define CGI_COLOR_ANTIQUEWHITE_ALPHA				1.000000

#define CGI_COLOR_LINEN_NAME						"Linen"
#define CGI_COLOR_LINEN_RED							0.976562
#define CGI_COLOR_LINEN_GREEN						0.937500
#define CGI_COLOR_LINEN_BLUE						0.898438
#define CGI_COLOR_LINEN_ALPHA						1.000000

#define CGI_COLOR_LAVENDERBLUSH_NAME				"LavenderBlush"
#define CGI_COLOR_LAVENDERBLUSH_RED					0.996094
#define CGI_COLOR_LAVENDERBLUSH_GREEN				0.937500
#define CGI_COLOR_LAVENDERBLUSH_BLUE				0.957031
#define CGI_COLOR_LAVENDERBLUSH_ALPHA				1.000000

#define CGI_COLOR_MISTYROSE_NAME					"MistyRose"
#define CGI_COLOR_MISTYROSE_RED						0.996094
#define CGI_COLOR_MISTYROSE_GREEN					0.890625
#define CGI_COLOR_MISTYROSE_BLUE					0.878906
#define CGI_COLOR_MISTYROSE_ALPHA					1.000000

// gray colors

#define CGI_COLOR_GAINSBORO_NAME					"Gainsboro"
#define CGI_COLOR_GAINSBORO_RED						0.859375
#define CGI_COLOR_GAINSBORO_GREEN					0.859375
#define CGI_COLOR_GAINSBORO_BLUE					0.859375
#define CGI_COLOR_GAINSBORO_ALPHA					1.000000

#define CGI_COLOR_LIGHTGREY_NAME					"LightGrey"
#define CGI_COLOR_LIGHTGREY_RED						0.824219
#define CGI_COLOR_LIGHTGREY_GREEN					0.824219
#define CGI_COLOR_LIGHTGREY_BLUE					0.824219
#define CGI_COLOR_LIGHTGREY_ALPHA					1.000000

#define CGI_COLOR_SILVER_NAME						"Silver"
#define CGI_COLOR_SILVER_RED						0.750000
#define CGI_COLOR_SILVER_GREEN						0.750000
#define CGI_COLOR_SILVER_BLUE						0.750000
#define CGI_COLOR_SILVER_ALPHA						1.000000

#define CGI_COLOR_DARKGRAY_NAME						"DarkGray"
#define CGI_COLOR_DARKGRAY_RED						0.660156
#define CGI_COLOR_DARKGRAY_GREEN					0.660156
#define CGI_COLOR_DARKGRAY_BLUE						0.660156
#define CGI_COLOR_DARKGRAY_ALPHA					1.000000

#define CGI_COLOR_GRAY_NAME							"Gray"
#define CGI_COLOR_GRAY_RED							0.500000
#define CGI_COLOR_GRAY_GREEN						0.500000
#define CGI_COLOR_GRAY_BLUE							0.500000
#define CGI_COLOR_GRAY_ALPHA						1.000000

#define CGI_COLOR_DIMGRAY_NAME						"DimGray"
#define CGI_COLOR_DIMGRAY_RED						0.410156
#define CGI_COLOR_DIMGRAY_GREEN						0.410156
#define CGI_COLOR_DIMGRAY_BLUE						0.410156
#define CGI_COLOR_DIMGRAY_ALPHA						1.000000

#define CGI_COLOR_LIGHTSLATEGRAY_NAME				"LightSlateGray"
#define CGI_COLOR_LIGHTSLATEGRAY_RED				0.464844
#define CGI_COLOR_LIGHTSLATEGRAY_GREEN				0.531250
#define CGI_COLOR_LIGHTSLATEGRAY_BLUE				0.597656
#define CGI_COLOR_LIGHTSLATEGRAY_ALPHA				1.000000

#define CGI_COLOR_SLATEGRAY_NAME					"SlateGray"
#define CGI_COLOR_SLATEGRAY_RED						0.437500
#define CGI_COLOR_SLATEGRAY_GREEN					0.500000
#define CGI_COLOR_SLATEGRAY_BLUE					0.562500
#define CGI_COLOR_SLATEGRAY_ALPHA					1.000000

#define CGI_COLOR_DARKSLATEGRAY_NAME				"DarkSlateGray"
#define CGI_COLOR_DARKSLATEGRAY_RED					0.183594
#define CGI_COLOR_DARKSLATEGRAY_GREEN				0.308594
#define CGI_COLOR_DARKSLATEGRAY_BLUE				0.308594
#define CGI_COLOR_DARKSLATEGRAY_ALPHA				1.000000

#define CGI_COLOR_BLACK_NAME						"Black"
#define CGI_COLOR_BLACK_RED							0.000000
#define CGI_COLOR_BLACK_GREEN						0.000000
#define CGI_COLOR_BLACK_BLUE						0.000000
#define CGI_COLOR_BLACK_ALPHA						1.000000


// define RGBA color application macros

// red colors

#define CGI_COLOR_INDIANRED \
	cgi_glColor4d(CGI_COLOR_INDIANRED_RED, \
			CGI_COLOR_INDIANRED_GREEN, \
			CGI_COLOR_INDIANRED_BLUE, \
			CGI_COLOR_INDIANRED_ALPHA)

#define CGI_COLOR_LIGHTCORAL \
	cgi_glColor4d(CGI_COLOR_LIGHTCORAL_RED, \
			CGI_COLOR_LIGHTCORAL_GREEN, \
			CGI_COLOR_LIGHTCORAL_BLUE, \
			CGI_COLOR_LIGHTCORAL_ALPHA)

#define CGI_COLOR_SALMON \
	cgi_glColor4d(CGI_COLOR_SALMON_RED, \
			CGI_COLOR_SALMON_GREEN, \
			CGI_COLOR_SALMON_BLUE, \
			CGI_COLOR_SALMON_ALPHA)

#define CGI_COLOR_DARKSALMON \
	cgi_glColor4d(CGI_COLOR_DARKSALMON_RED, \
			CGI_COLOR_DARKSALMON_GREEN, \
			CGI_COLOR_DARKSALMON_BLUE, \
			CGI_COLOR_DARKSALMON_ALPHA)

#define CGI_COLOR_LIGHTSALMON \
	cgi_glColor4d(CGI_COLOR_LIGHTSALMON_RED, \
			CGI_COLOR_LIGHTSALMON_GREEN, \
			CGI_COLOR_LIGHTSALMON_BLUE, \
			CGI_COLOR_LIGHTSALMON_ALPHA)

#define CGI_COLOR_CRIMSON \
	cgi_glColor4d(CGI_COLOR_CRIMSON_RED, \
			CGI_COLOR_CRIMSON_GREEN, \
			CGI_COLOR_CRIMSON_BLUE, \
			CGI_COLOR_CRIMSON_ALPHA)

#define CGI_COLOR_RED \
	cgi_glColor4d(CGI_COLOR_RED_RED, \
			CGI_COLOR_RED_GREEN, \
			CGI_COLOR_RED_BLUE, \
			CGI_COLOR_RED_ALPHA)

#define CGI_COLOR_FIREBRICK \
	cgi_glColor4d(CGI_COLOR_FIREBRICK_RED, \
			CGI_COLOR_FIREBRICK_GREEN, \
			CGI_COLOR_FIREBRICK_BLUE, \
			CGI_COLOR_FIREBRICK_ALPHA)

#define CGI_COLOR_DARKRED \
	cgi_glColor4d(CGI_COLOR_DARKRED_RED, \
			CGI_COLOR_DARKRED_GREEN, \
			CGI_COLOR_DARKRED_BLUE, \
			CGI_COLOR_DARKRED_ALPHA)

// pink colors

#define CGI_COLOR_PINK \
	cgi_glColor4d(CGI_COLOR_PINK_RED, \
			CGI_COLOR_PINK_GREEN, \
			CGI_COLOR_PINK_BLUE, \
			CGI_COLOR_PINK_ALPHA)

#define CGI_COLOR_LIGHTPINK \
	cgi_glColor4d(CGI_COLOR_LIGHTPINK_RED, \
			CGI_COLOR_LIGHTPINK_GREEN, \
			CGI_COLOR_LIGHTPINK_BLUE, \
			CGI_COLOR_LIGHTPINK_ALPHA)

#define CGI_COLOR_HOTPINK \
	cgi_glColor4d(CGI_COLOR_HOTPINK_RED, \
			CGI_COLOR_HOTPINK_GREEN, \
			CGI_COLOR_HOTPINK_BLUE, \
			CGI_COLOR_HOTPINK_ALPHA)

#define CGI_COLOR_DEEPPINK \
	cgi_glColor4d(CGI_COLOR_DEEPPINK_RED, \
			CGI_COLOR_DEEPPINK_GREEN, \
			CGI_COLOR_DEEPPINK_BLUE, \
			CGI_COLOR_DEEPPINK_ALPHA)

#define CGI_COLOR_MEDIUMVIOLETRED \
	cgi_glColor4d(CGI_COLOR_MEDIUMVIOLETRED_RED, \
			CGI_COLOR_MEDIUMVIOLETRED_GREEN, \
			CGI_COLOR_MEDIUMVIOLETRED_BLUE, \
			CGI_COLOR_MEDIUMVIOLETRED_ALPHA)

#define CGI_COLOR_PALEVIOLETRED \
	cgi_glColor4d(CGI_COLOR_PALEVIOLETRED_RED, \
			CGI_COLOR_PALEVIOLETRED_GREEN, \
			CGI_COLOR_PALEVIOLETRED_BLUE, \
			CGI_COLOR_PALEVIOLETRED_ALPHA)

// orange colors

#define CGI_COLOR_LIGHTSALMON \
	cgi_glColor4d(CGI_COLOR_LIGHTSALMON_RED, \
			CGI_COLOR_LIGHTSALMON_GREEN, \
			CGI_COLOR_LIGHTSALMON_BLUE, \
			CGI_COLOR_LIGHTSALMON_ALPHA)

#define CGI_COLOR_CORAL \
	cgi_glColor4d(CGI_COLOR_CORAL_RED, \
			CGI_COLOR_CORAL_GREEN, \
			CGI_COLOR_CORAL_BLUE, \
			CGI_COLOR_CORAL_ALPHA)

#define CGI_COLOR_TOMATO \
	cgi_glColor4d(CGI_COLOR_TOMATO_RED, \
			CGI_COLOR_TOMATO_GREEN, \
			CGI_COLOR_TOMATO_BLUE, \
			CGI_COLOR_TOMATO_ALPHA)

#define CGI_COLOR_ORANGERED \
	cgi_glColor4d(CGI_COLOR_ORANGERED_RED, \
			CGI_COLOR_ORANGERED_GREEN, \
			CGI_COLOR_ORANGERED_BLUE, \
			CGI_COLOR_ORANGERED_ALPHA)

#define CGI_COLOR_DARKORANGE \
	cgi_glColor4d(CGI_COLOR_DARKORANGE_RED, \
			CGI_COLOR_DARKORANGE_GREEN, \
			CGI_COLOR_DARKORANGE_BLUE, \
			CGI_COLOR_DARKORANGE_ALPHA)

#define CGI_COLOR_ORANGE \
	cgi_glColor4d(CGI_COLOR_ORANGE_RED, \
			CGI_COLOR_ORANGE_GREEN, \
			CGI_COLOR_ORANGE_BLUE, \
			CGI_COLOR_ORANGE_ALPHA)

// yellow colors

#define CGI_COLOR_GOLD \
	cgi_glColor4d(CGI_COLOR_GOLD_RED, \
			CGI_COLOR_GOLD_GREEN, \
			CGI_COLOR_GOLD_BLUE, \
			CGI_COLOR_GOLD_ALPHA)

#define CGI_COLOR_YELLOW \
	cgi_glColor4d(CGI_COLOR_YELLOW_RED, \
			CGI_COLOR_YELLOW_GREEN, \
			CGI_COLOR_YELLOW_BLUE, \
			CGI_COLOR_YELLOW_ALPHA)

#define CGI_COLOR_LIGHTYELLOW \
	cgi_glColor4d(CGI_COLOR_LIGHTYELLOW_RED, \
			CGI_COLOR_LIGHTYELLOW_GREEN, \
			CGI_COLOR_LIGHTYELLOW_BLUE, \
			CGI_COLOR_LIGHTYELLOW_ALPHA)

#define CGI_COLOR_LEMONCHIFFON \
	cgi_glColor4d(CGI_COLOR_LEMONCHIFFON_RED, \
			CGI_COLOR_LEMONCHIFFON_GREEN, \
			CGI_COLOR_LEMONCHIFFON_BLUE, \
			CGI_COLOR_LEMONCHIFFON_ALPHA)

#define CGI_COLOR_LIGHTGOLDENRODYELLOW \
	cgi_glColor4d(CGI_COLOR_LIGHTGOLDENRODYELLOW_RED, \
			CGI_COLOR_LIGHTGOLDENRODYELLOW_GREEN, \
			CGI_COLOR_LIGHTGOLDENRODYELLOW_BLUE, \
			CGI_COLOR_LIGHTGOLDENRODYELLOW_ALPHA)

#define CGI_COLOR_PAPAYAWHIP \
	cgi_glColor4d(CGI_COLOR_PAPAYAWHIP_RED, \
			CGI_COLOR_PAPAYAWHIP_GREEN, \
			CGI_COLOR_PAPAYAWHIP_BLUE, \
			CGI_COLOR_PAPAYAWHIP_ALPHA)

#define CGI_COLOR_MOCCASIN \
	cgi_glColor4d(CGI_COLOR_MOCCASIN_RED, \
			CGI_COLOR_MOCCASIN_GREEN, \
			CGI_COLOR_MOCCASIN_BLUE, \
			CGI_COLOR_MOCCASIN_ALPHA)

#define CGI_COLOR_PEACHPUFF \
	cgi_glColor4d(CGI_COLOR_PEACHPUFF_RED, \
			CGI_COLOR_PEACHPUFF_GREEN, \
			CGI_COLOR_PEACHPUFF_BLUE, \
			CGI_COLOR_PEACHPUFF_ALPHA)

#define CGI_COLOR_PALEGOLDENROD \
	cgi_glColor4d(CGI_COLOR_PALEGOLDENROD_RED, \
			CGI_COLOR_PALEGOLDENROD_GREEN, \
			CGI_COLOR_PALEGOLDENROD_BLUE, \
			CGI_COLOR_PALEGOLDENROD_ALPHA)

#define CGI_COLOR_KHAKI \
	cgi_glColor4d(CGI_COLOR_KHAKI_RED, \
			CGI_COLOR_KHAKI_GREEN, \
			CGI_COLOR_KHAKI_BLUE, \
			CGI_COLOR_KHAKI_ALPHA)

#define CGI_COLOR_DARKKHAKI \
	cgi_glColor4d(CGI_COLOR_DARKKHAKI_RED, \
			CGI_COLOR_DARKKHAKI_GREEN, \
			CGI_COLOR_DARKKHAKI_BLUE, \
			CGI_COLOR_DARKKHAKI_ALPHA)

// purple colors

#define CGI_COLOR_LAVENDER \
	cgi_glColor4d(CGI_COLOR_LAVENDER_RED, \
			CGI_COLOR_LAVENDER_GREEN, \
			CGI_COLOR_LAVENDER_BLUE, \
			CGI_COLOR_LAVENDER_ALPHA)

#define CGI_COLOR_THISTLE \
	cgi_glColor4d(CGI_COLOR_THISTLE_RED, \
			CGI_COLOR_THISTLE_GREEN, \
			CGI_COLOR_THISTLE_BLUE, \
			CGI_COLOR_THISTLE_ALPHA)

#define CGI_COLOR_PLUM \
	cgi_glColor4d(CGI_COLOR_PLUM_RED, \
			CGI_COLOR_PLUM_GREEN, \
			CGI_COLOR_PLUM_BLUE, \
			CGI_COLOR_PLUM_ALPHA)

#define CGI_COLOR_VIOLET \
	cgi_glColor4d(CGI_COLOR_VIOLET_RED, \
			CGI_COLOR_VIOLET_GREEN, \
			CGI_COLOR_VIOLET_BLUE, \
			CGI_COLOR_VIOLET_ALPHA)

#define CGI_COLOR_ORCHID \
	cgi_glColor4d(CGI_COLOR_ORCHID_RED, \
			CGI_COLOR_ORCHID_GREEN, \
			CGI_COLOR_ORCHID_BLUE, \
			CGI_COLOR_ORCHID_ALPHA)

#define CGI_COLOR_FUCHSIA \
	cgi_glColor4d(CGI_COLOR_FUCHSIA_RED, \
			CGI_COLOR_FUCHSIA_GREEN, \
			CGI_COLOR_FUCHSIA_BLUE, \
			CGI_COLOR_FUCHSIA_ALPHA)

#define CGI_COLOR_MAGENTA \
	cgi_glColor4d(CGI_COLOR_MAGENTA_RED, \
			CGI_COLOR_MAGENTA_GREEN, \
			CGI_COLOR_MAGENTA_BLUE, \
			CGI_COLOR_MAGENTA_ALPHA)

#define CGI_COLOR_MEDIUMORCHID \
	cgi_glColor4d(CGI_COLOR_MEDIUMORCHID_RED, \
			CGI_COLOR_MEDIUMORCHID_GREEN, \
			CGI_COLOR_MEDIUMORCHID_BLUE, \
			CGI_COLOR_MEDIUMORCHID_ALPHA)

#define CGI_COLOR_MEDIUMPURPLE \
	cgi_glColor4d(CGI_COLOR_MEDIUMPURPLE_RED, \
			CGI_COLOR_MEDIUMPURPLE_GREEN, \
			CGI_COLOR_MEDIUMPURPLE_BLUE, \
			CGI_COLOR_MEDIUMPURPLE_ALPHA)

#define CGI_COLOR_AMETHYST \
	cgi_glColor4d(CGI_COLOR_AMETHYST_RED, \
			CGI_COLOR_AMETHYST_GREEN, \
			CGI_COLOR_AMETHYST_BLUE, \
			CGI_COLOR_AMETHYST_ALPHA)

#define CGI_COLOR_BLUEVIOLET \
	cgi_glColor4d(CGI_COLOR_BLUEVIOLET_RED, \
			CGI_COLOR_BLUEVIOLET_GREEN, \
			CGI_COLOR_BLUEVIOLET_BLUE, \
			CGI_COLOR_BLUEVIOLET_ALPHA)

#define CGI_COLOR_DARKVIOLET \
	cgi_glColor4d(CGI_COLOR_DARKVIOLET_RED, \
			CGI_COLOR_DARKVIOLET_GREEN, \
			CGI_COLOR_DARKVIOLET_BLUE, \
			CGI_COLOR_DARKVIOLET_ALPHA)

#define CGI_COLOR_DARKORCHID \
	cgi_glColor4d(CGI_COLOR_DARKORCHID_RED, \
			CGI_COLOR_DARKORCHID_GREEN, \
			CGI_COLOR_DARKORCHID_BLUE, \
			CGI_COLOR_DARKORCHID_ALPHA)

#define CGI_COLOR_DARKMAGENTA \
	cgi_glColor4d(CGI_COLOR_DARKMAGENTA_RED, \
			CGI_COLOR_DARKMAGENTA_GREEN, \
			CGI_COLOR_DARKMAGENTA_BLUE, \
			CGI_COLOR_DARKMAGENTA_ALPHA)

#define CGI_COLOR_PURPLE \
	cgi_glColor4d(CGI_COLOR_PURPLE_RED, \
			CGI_COLOR_PURPLE_GREEN, \
			CGI_COLOR_PURPLE_BLUE, \
			CGI_COLOR_PURPLE_ALPHA)

#define CGI_COLOR_INDIGO \
	cgi_glColor4d(CGI_COLOR_INDIGO_RED, \
			CGI_COLOR_INDIGO_GREEN, \
			CGI_COLOR_INDIGO_BLUE, \
			CGI_COLOR_INDIGO_ALPHA)

#define CGI_COLOR_SLATEBLUE \
	cgi_glColor4d(CGI_COLOR_SLATEBLUE_RED, \
			CGI_COLOR_SLATEBLUE_GREEN, \
			CGI_COLOR_SLATEBLUE_BLUE, \
			CGI_COLOR_SLATEBLUE_ALPHA)

#define CGI_COLOR_DARKSLATEBLUE \
	cgi_glColor4d(CGI_COLOR_DARKSLATEBLUE_RED, \
			CGI_COLOR_DARKSLATEBLUE_GREEN, \
			CGI_COLOR_DARKSLATEBLUE_BLUE, \
			CGI_COLOR_DARKSLATEBLUE_ALPHA)

#define CGI_COLOR_MEDIUMSLATEBLUE \
	cgi_glColor4d(CGI_COLOR_MEDIUMSLATEBLUE_RED, \
			CGI_COLOR_MEDIUMSLATEBLUE_GREEN, \
			CGI_COLOR_MEDIUMSLATEBLUE_BLUE, \
			CGI_COLOR_MEDIUMSLATEBLUE_ALPHA)

// green colors

#define CGI_COLOR_GREENYELLOW \
	cgi_glColor4d(CGI_COLOR_GREENYELLOW_RED, \
			CGI_COLOR_GREENYELLOW_GREEN, \
			CGI_COLOR_GREENYELLOW_BLUE, \
			CGI_COLOR_GREENYELLOW_ALPHA)

#define CGI_COLOR_CHARTREUSE \
	cgi_glColor4d(CGI_COLOR_CHARTREUSE_RED, \
			CGI_COLOR_CHARTREUSE_GREEN, \
			CGI_COLOR_CHARTREUSE_BLUE, \
			CGI_COLOR_CHARTREUSE_ALPHA)

#define CGI_COLOR_LAWNGREEN \
	cgi_glColor4d(CGI_COLOR_LAWNGREEN_RED, \
			CGI_COLOR_LAWNGREEN_GREEN, \
			CGI_COLOR_LAWNGREEN_BLUE, \
			CGI_COLOR_LAWNGREEN_ALPHA)

#define CGI_COLOR_LIME \
	cgi_glColor4d(CGI_COLOR_LIME_RED, \
			CGI_COLOR_LIME_GREEN, \
			CGI_COLOR_LIME_BLUE, \
			CGI_COLOR_LIME_ALPHA)

#define CGI_COLOR_LIMEGREEN \
	cgi_glColor4d(CGI_COLOR_LIMEGREEN_RED, \
			CGI_COLOR_LIMEGREEN_GREEN, \
			CGI_COLOR_LIMEGREEN_BLUE, \
			CGI_COLOR_LIMEGREEN_ALPHA)

#define CGI_COLOR_PALEGREEN \
	cgi_glColor4d(CGI_COLOR_PALEGREEN_RED, \
			CGI_COLOR_PALEGREEN_GREEN, \
			CGI_COLOR_PALEGREEN_BLUE, \
			CGI_COLOR_PALEGREEN_ALPHA)

#define CGI_COLOR_LIGHTGREEN \
	cgi_glColor4d(CGI_COLOR_LIGHTGREEN_RED, \
			CGI_COLOR_LIGHTGREEN_GREEN, \
			CGI_COLOR_LIGHTGREEN_BLUE, \
			CGI_COLOR_LIGHTGREEN_ALPHA)

#define CGI_COLOR_MEDIUMSPRINGGREEN \
	cgi_glColor4d(CGI_COLOR_MEDIUMSPRINGGREEN_RED, \
			CGI_COLOR_MEDIUMSPRINGGREEN_GREEN, \
			CGI_COLOR_MEDIUMSPRINGGREEN_BLUE, \
			CGI_COLOR_MEDIUMSPRINGGREEN_ALPHA)

#define CGI_COLOR_SPRINGGREEN \
	cgi_glColor4d(CGI_COLOR_SPRINGGREEN_RED, \
			CGI_COLOR_SPRINGGREEN_GREEN, \
			CGI_COLOR_SPRINGGREEN_BLUE, \
			CGI_COLOR_SPRINGGREEN_ALPHA)

#define CGI_COLOR_MEDIUMSEAGREEN \
	cgi_glColor4d(CGI_COLOR_MEDIUMSEAGREEN_RED, \
			CGI_COLOR_MEDIUMSEAGREEN_GREEN, \
			CGI_COLOR_MEDIUMSEAGREEN_BLUE, \
			CGI_COLOR_MEDIUMSEAGREEN_ALPHA)

#define CGI_COLOR_SEAGREEN \
	cgi_glColor4d(CGI_COLOR_SEAGREEN_RED, \
			CGI_COLOR_SEAGREEN_GREEN, \
			CGI_COLOR_SEAGREEN_BLUE, \
			CGI_COLOR_SEAGREEN_ALPHA)

#define CGI_COLOR_FORESTGREEN \
	cgi_glColor4d(CGI_COLOR_FORESTGREEN_RED, \
			CGI_COLOR_FORESTGREEN_GREEN, \
			CGI_COLOR_FORESTGREEN_BLUE, \
			CGI_COLOR_FORESTGREEN_ALPHA)

#define CGI_COLOR_GREEN \
	cgi_glColor4d(CGI_COLOR_GREEN_RED, \
			CGI_COLOR_GREEN_GREEN, \
			CGI_COLOR_GREEN_BLUE, \
			CGI_COLOR_GREEN_ALPHA)

#define CGI_COLOR_DARKGREEN \
	cgi_glColor4d(CGI_COLOR_DARKGREEN_RED, \
			CGI_COLOR_DARKGREEN_GREEN, \
			CGI_COLOR_DARKGREEN_BLUE, \
			CGI_COLOR_DARKGREEN_ALPHA)

#define CGI_COLOR_YELLOWGREEN \
	cgi_glColor4d(CGI_COLOR_YELLOWGREEN_RED, \
			CGI_COLOR_YELLOWGREEN_GREEN, \
			CGI_COLOR_YELLOWGREEN_BLUE, \
			CGI_COLOR_YELLOWGREEN_ALPHA)

#define CGI_COLOR_OLIVEDRAB \
	cgi_glColor4d(CGI_COLOR_OLIVEDRAB_RED, \
			CGI_COLOR_OLIVEDRAB_GREEN, \
			CGI_COLOR_OLIVEDRAB_BLUE, \
			CGI_COLOR_OLIVEDRAB_ALPHA)

#define CGI_COLOR_OLIVE \
	cgi_glColor4d(CGI_COLOR_OLIVE_RED, \
			CGI_COLOR_OLIVE_GREEN, \
			CGI_COLOR_OLIVE_BLUE, \
			CGI_COLOR_OLIVE_ALPHA)

#define CGI_COLOR_DARKOLIVEGREEN \
	cgi_glColor4d(CGI_COLOR_DARKOLIVEGREEN_RED, \
			CGI_COLOR_DARKOLIVEGREEN_GREEN, \
			CGI_COLOR_DARKOLIVEGREEN_BLUE, \
			CGI_COLOR_DARKOLIVEGREEN_ALPHA)

#define CGI_COLOR_MEDIUMAQUAMARINE \
	cgi_glColor4d(CGI_COLOR_MEDIUMAQUAMARINE_RED, \
			CGI_COLOR_MEDIUMAQUAMARINE_GREEN, \
			CGI_COLOR_MEDIUMAQUAMARINE_BLUE, \
			CGI_COLOR_MEDIUMAQUAMARINE_ALPHA)

#define CGI_COLOR_DARKSEAGREEN \
	cgi_glColor4d(CGI_COLOR_DARKSEAGREEN_RED, \
			CGI_COLOR_DARKSEAGREEN_GREEN, \
			CGI_COLOR_DARKSEAGREEN_BLUE, \
			CGI_COLOR_DARKSEAGREEN_ALPHA)

#define CGI_COLOR_LIGHTSEAGREEN \
	cgi_glColor4d(CGI_COLOR_LIGHTSEAGREEN_RED, \
			CGI_COLOR_LIGHTSEAGREEN_GREEN, \
			CGI_COLOR_LIGHTSEAGREEN_BLUE, \
			CGI_COLOR_LIGHTSEAGREEN_ALPHA)

#define CGI_COLOR_DARKCYAN \
	cgi_glColor4d(CGI_COLOR_DARKCYAN_RED, \
			CGI_COLOR_DARKCYAN_GREEN, \
			CGI_COLOR_DARKCYAN_BLUE, \
			CGI_COLOR_DARKCYAN_ALPHA)

#define CGI_COLOR_TEAL \
	cgi_glColor4d(CGI_COLOR_TEAL_RED, \
			CGI_COLOR_TEAL_GREEN, \
			CGI_COLOR_TEAL_BLUE, \
			CGI_COLOR_TEAL_ALPHA)

// blue colors

#define CGI_COLOR_AQUA \
	cgi_glColor4d(CGI_COLOR_AQUA_RED, \
			CGI_COLOR_AQUA_GREEN, \
			CGI_COLOR_AQUA_BLUE, \
			CGI_COLOR_AQUA_ALPHA)

#define CGI_COLOR_CYAN \
	cgi_glColor4d(CGI_COLOR_CYAN_RED, \
			CGI_COLOR_CYAN_GREEN, \
			CGI_COLOR_CYAN_BLUE, \
			CGI_COLOR_CYAN_ALPHA)

#define CGI_COLOR_LIGHTCYAN \
	cgi_glColor4d(CGI_COLOR_LIGHTCYAN_RED, \
			CGI_COLOR_LIGHTCYAN_GREEN, \
			CGI_COLOR_LIGHTCYAN_BLUE, \
			CGI_COLOR_LIGHTCYAN_ALPHA)

#define CGI_COLOR_PALETURQUOISE \
	cgi_glColor4d(CGI_COLOR_PALETURQUOISE_RED, \
			CGI_COLOR_PALETURQUOISE_GREEN, \
			CGI_COLOR_PALETURQUOISE_BLUE, \
			CGI_COLOR_PALETURQUOISE_ALPHA)

#define CGI_COLOR_AQUAMARINE \
	cgi_glColor4d(CGI_COLOR_AQUAMARINE_RED, \
			CGI_COLOR_AQUAMARINE_GREEN, \
			CGI_COLOR_AQUAMARINE_BLUE, \
			CGI_COLOR_AQUAMARINE_ALPHA)

#define CGI_COLOR_TURQUOISE \
	cgi_glColor4d(CGI_COLOR_TURQUOISE_RED, \
			CGI_COLOR_TURQUOISE_GREEN, \
			CGI_COLOR_TURQUOISE_BLUE, \
			CGI_COLOR_TURQUOISE_ALPHA)

#define CGI_COLOR_MEDIUMTURQUOISE \
	cgi_glColor4d(CGI_COLOR_MEDIUMTURQUOISE_RED, \
			CGI_COLOR_MEDIUMTURQUOISE_GREEN, \
			CGI_COLOR_MEDIUMTURQUOISE_BLUE, \
			CGI_COLOR_MEDIUMTURQUOISE_ALPHA)

#define CGI_COLOR_DARKTURQUOISE \
	cgi_glColor4d(CGI_COLOR_DARKTURQUOISE_RED, \
			CGI_COLOR_DARKTURQUOISE_GREEN, \
			CGI_COLOR_DARKTURQUOISE_BLUE, \
			CGI_COLOR_DARKTURQUOISE_ALPHA)

#define CGI_COLOR_CADETBLUE \
	cgi_glColor4d(CGI_COLOR_CADETBLUE_RED, \
			CGI_COLOR_CADETBLUE_GREEN, \
			CGI_COLOR_CADETBLUE_BLUE, \
			CGI_COLOR_CADETBLUE_ALPHA)

#define CGI_COLOR_STEELBLUE \
	cgi_glColor4d(CGI_COLOR_STEELBLUE_RED, \
			CGI_COLOR_STEELBLUE_GREEN, \
			CGI_COLOR_STEELBLUE_BLUE, \
			CGI_COLOR_STEELBLUE_ALPHA)

#define CGI_COLOR_LIGHTSTEELBLUE \
	cgi_glColor4d(CGI_COLOR_LIGHTSTEELBLUE_RED, \
			CGI_COLOR_LIGHTSTEELBLUE_GREEN, \
			CGI_COLOR_LIGHTSTEELBLUE_BLUE, \
			CGI_COLOR_LIGHTSTEELBLUE_ALPHA)

#define CGI_COLOR_POWDERBLUE \
	cgi_glColor4d(CGI_COLOR_POWDERBLUE_RED, \
			CGI_COLOR_POWDERBLUE_GREEN, \
			CGI_COLOR_POWDERBLUE_BLUE, \
			CGI_COLOR_POWDERBLUE_ALPHA)

#define CGI_COLOR_LIGHTBLUE \
	cgi_glColor4d(CGI_COLOR_LIGHTBLUE_RED, \
			CGI_COLOR_LIGHTBLUE_GREEN, \
			CGI_COLOR_LIGHTBLUE_BLUE, \
			CGI_COLOR_LIGHTBLUE_ALPHA)

#define CGI_COLOR_SKYBLUE \
	cgi_glColor4d(CGI_COLOR_SKYBLUE_RED, \
			CGI_COLOR_SKYBLUE_GREEN, \
			CGI_COLOR_SKYBLUE_BLUE, \
			CGI_COLOR_SKYBLUE_ALPHA)

#define CGI_COLOR_LIGHTSKYBLUE \
	cgi_glColor4d(CGI_COLOR_LIGHTSKYBLUE_RED, \
			CGI_COLOR_LIGHTSKYBLUE_GREEN, \
			CGI_COLOR_LIGHTSKYBLUE_BLUE, \
			CGI_COLOR_LIGHTSKYBLUE_ALPHA)

#define CGI_COLOR_DEEPSKYBLUE \
	cgi_glColor4d(CGI_COLOR_DEEPSKYBLUE_RED, \
			CGI_COLOR_DEEPSKYBLUE_GREEN, \
			CGI_COLOR_DEEPSKYBLUE_BLUE, \
			CGI_COLOR_DEEPSKYBLUE_ALPHA)

#define CGI_COLOR_DODGERBLUE \
	cgi_glColor4d(CGI_COLOR_DODGERBLUE_RED, \
			CGI_COLOR_DODGERBLUE_GREEN, \
			CGI_COLOR_DODGERBLUE_BLUE, \
			CGI_COLOR_DODGERBLUE_ALPHA)

#define CGI_COLOR_CORNFLOWERBLUE \
	cgi_glColor4d(CGI_COLOR_CORNFLOWERBLUE_RED, \
			CGI_COLOR_CORNFLOWERBLUE_GREEN, \
			CGI_COLOR_CORNFLOWERBLUE_BLUE, \
			CGI_COLOR_CORNFLOWERBLUE_ALPHA)

#define CGI_COLOR_MEDIUMSLATEBLUE \
	cgi_glColor4d(CGI_COLOR_MEDIUMSLATEBLUE_RED, \
			CGI_COLOR_MEDIUMSLATEBLUE_GREEN, \
			CGI_COLOR_MEDIUMSLATEBLUE_BLUE, \
			CGI_COLOR_MEDIUMSLATEBLUE_ALPHA)

#define CGI_COLOR_ROYALBLUE \
	cgi_glColor4d(CGI_COLOR_ROYALBLUE_RED, \
			CGI_COLOR_ROYALBLUE_GREEN, \
			CGI_COLOR_ROYALBLUE_BLUE, \
			CGI_COLOR_ROYALBLUE_ALPHA)

#define CGI_COLOR_BLUE \
	cgi_glColor4d(CGI_COLOR_BLUE_RED, \
			CGI_COLOR_BLUE_GREEN, \
			CGI_COLOR_BLUE_BLUE, \
			CGI_COLOR_BLUE_ALPHA)

#define CGI_COLOR_MEDIUMBLUE \
	cgi_glColor4d(CGI_COLOR_MEDIUMBLUE_RED, \
			CGI_COLOR_MEDIUMBLUE_GREEN, \
			CGI_COLOR_MEDIUMBLUE_BLUE, \
			CGI_COLOR_MEDIUMBLUE_ALPHA)

#define CGI_COLOR_DARKBLUE \
	cgi_glColor4d(CGI_COLOR_DARKBLUE_RED, \
			CGI_COLOR_DARKBLUE_GREEN, \
			CGI_COLOR_DARKBLUE_BLUE, \
			CGI_COLOR_DARKBLUE_ALPHA)

#define CGI_COLOR_NAVY \
	cgi_glColor4d(CGI_COLOR_NAVY_RED, \
			CGI_COLOR_NAVY_GREEN, \
			CGI_COLOR_NAVY_BLUE, \
			CGI_COLOR_NAVY_ALPHA)

#define CGI_COLOR_MIDNIGHTBLUE \
	cgi_glColor4d(CGI_COLOR_MIDNIGHTBLUE_RED, \
			CGI_COLOR_MIDNIGHTBLUE_GREEN, \
			CGI_COLOR_MIDNIGHTBLUE_BLUE, \
			CGI_COLOR_MIDNIGHTBLUE_ALPHA)

// brown colors

#define CGI_COLOR_CORNSILK \
	cgi_glColor4d(CGI_COLOR_CORNSILK_RED, \
			CGI_COLOR_CORNSILK_GREEN, \
			CGI_COLOR_CORNSILK_BLUE, \
			CGI_COLOR_CORNSILK_ALPHA)

#define CGI_COLOR_BLANCHEDALMOND \
	cgi_glColor4d(CGI_COLOR_BLANCHEDALMOND_RED, \
			CGI_COLOR_BLANCHEDALMOND_GREEN, \
			CGI_COLOR_BLANCHEDALMOND_BLUE, \
			CGI_COLOR_BLANCHEDALMOND_ALPHA)

#define CGI_COLOR_BISQUE \
	cgi_glColor4d(CGI_COLOR_BISQUE_RED, \
			CGI_COLOR_BISQUE_GREEN, \
			CGI_COLOR_BISQUE_BLUE, \
			CGI_COLOR_BISQUE_ALPHA)

#define CGI_COLOR_NAVAJOWHITE \
	cgi_glColor4d(CGI_COLOR_NAVAJOWHITE_RED, \
			CGI_COLOR_NAVAJOWHITE_GREEN, \
			CGI_COLOR_NAVAJOWHITE_BLUE, \
			CGI_COLOR_NAVAJOWHITE_ALPHA)

#define CGI_COLOR_WHEAT \
	cgi_glColor4d(CGI_COLOR_WHEAT_RED, \
			CGI_COLOR_WHEAT_GREEN, \
			CGI_COLOR_WHEAT_BLUE, \
			CGI_COLOR_WHEAT_ALPHA)

#define CGI_COLOR_BURLYWOOD \
	cgi_glColor4d(CGI_COLOR_BURLYWOOD_RED, \
			CGI_COLOR_BURLYWOOD_GREEN, \
			CGI_COLOR_BURLYWOOD_BLUE, \
			CGI_COLOR_BURLYWOOD_ALPHA)

#define CGI_COLOR_TAN \
	cgi_glColor4d(CGI_COLOR_TAN_RED, \
			CGI_COLOR_TAN_GREEN, \
			CGI_COLOR_TAN_BLUE, \
			CGI_COLOR_TAN_ALPHA)

#define CGI_COLOR_ROSYBROWN \
	cgi_glColor4d(CGI_COLOR_ROSYBROWN_RED, \
			CGI_COLOR_ROSYBROWN_GREEN, \
			CGI_COLOR_ROSYBROWN_BLUE, \
			CGI_COLOR_ROSYBROWN_ALPHA)

#define CGI_COLOR_SANDYBROWN \
	cgi_glColor4d(CGI_COLOR_SANDYBROWN_RED, \
			CGI_COLOR_SANDYBROWN_GREEN, \
			CGI_COLOR_SANDYBROWN_BLUE, \
			CGI_COLOR_SANDYBROWN_ALPHA)

#define CGI_COLOR_GOLDENROD \
	cgi_glColor4d(CGI_COLOR_GOLDENROD_RED, \
			CGI_COLOR_GOLDENROD_GREEN, \
			CGI_COLOR_GOLDENROD_BLUE, \
			CGI_COLOR_GOLDENROD_ALPHA)

#define CGI_COLOR_DARKGOLDENROD \
	cgi_glColor4d(CGI_COLOR_DARKGOLDENROD_RED, \
			CGI_COLOR_DARKGOLDENROD_GREEN, \
			CGI_COLOR_DARKGOLDENROD_BLUE, \
			CGI_COLOR_DARKGOLDENROD_ALPHA)

#define CGI_COLOR_PERU \
	cgi_glColor4d(CGI_COLOR_PERU_RED, \
			CGI_COLOR_PERU_GREEN, \
			CGI_COLOR_PERU_BLUE, \
			CGI_COLOR_PERU_ALPHA)

#define CGI_COLOR_CHOCOLATE \
	cgi_glColor4d(CGI_COLOR_CHOCOLATE_RED, \
			CGI_COLOR_CHOCOLATE_GREEN, \
			CGI_COLOR_CHOCOLATE_BLUE, \
			CGI_COLOR_CHOCOLATE_ALPHA)

#define CGI_COLOR_SADDLEBROWN \
	cgi_glColor4d(CGI_COLOR_SADDLEBROWN_RED, \
			CGI_COLOR_SADDLEBROWN_GREEN, \
			CGI_COLOR_SADDLEBROWN_BLUE, \
			CGI_COLOR_SADDLEBROWN_ALPHA)

#define CGI_COLOR_SIENNA \
	cgi_glColor4d(CGI_COLOR_SIENNA_RED, \
			CGI_COLOR_SIENNA_GREEN, \
			CGI_COLOR_SIENNA_BLUE, \
			CGI_COLOR_SIENNA_ALPHA)

#define CGI_COLOR_BROWN \
	cgi_glColor4d(CGI_COLOR_BROWN_RED, \
			CGI_COLOR_BROWN_GREEN, \
			CGI_COLOR_BROWN_BLUE, \
			CGI_COLOR_BROWN_ALPHA)

#define CGI_COLOR_MAROON \
	cgi_glColor4d(CGI_COLOR_MAROON_RED, \
			CGI_COLOR_MAROON_GREEN, \
			CGI_COLOR_MAROON_BLUE, \
			CGI_COLOR_MAROON_ALPHA)

// white colors

#define CGI_COLOR_WHITE \
	cgi_glColor4d(CGI_COLOR_WHITE_RED, \
			CGI_COLOR_WHITE_GREEN, \
			CGI_COLOR_WHITE_BLUE, \
			CGI_COLOR_WHITE_ALPHA)

#define CGI_COLOR_SNOW \
	cgi_glColor4d(CGI_COLOR_SNOW_RED, \
			CGI_COLOR_SNOW_GREEN, \
			CGI_COLOR_SNOW_BLUE, \
			CGI_COLOR_SNOW_ALPHA)

#define CGI_COLOR_HONEYDEW \
	cgi_glColor4d(CGI_COLOR_HONEYDEW_RED, \
			CGI_COLOR_HONEYDEW_GREEN, \
			CGI_COLOR_HONEYDEW_BLUE, \
			CGI_COLOR_HONEYDEW_ALPHA)

#define CGI_COLOR_MINTCREAM \
	cgi_glColor4d(CGI_COLOR_MINTCREAM_RED, \
			CGI_COLOR_MINTCREAM_GREEN, \
			CGI_COLOR_MINTCREAM_BLUE, \
			CGI_COLOR_MINTCREAM_ALPHA)

#define CGI_COLOR_AZURE \
	cgi_glColor4d(CGI_COLOR_AZURE_RED, \
			CGI_COLOR_AZURE_GREEN, \
			CGI_COLOR_AZURE_BLUE, \
			CGI_COLOR_AZURE_ALPHA)

#define CGI_COLOR_ALICEBLUE \
	cgi_glColor4d(CGI_COLOR_ALICEBLUE_RED, \
			CGI_COLOR_ALICEBLUE_GREEN, \
			CGI_COLOR_ALICEBLUE_BLUE, \
			CGI_COLOR_ALICEBLUE_ALPHA)

#define CGI_COLOR_GHOSTWHITE \
	cgi_glColor4d(CGI_COLOR_GHOSTWHITE_RED, \
			CGI_COLOR_GHOSTWHITE_GREEN, \
			CGI_COLOR_GHOSTWHITE_BLUE, \
			CGI_COLOR_GHOSTWHITE_ALPHA)

#define CGI_COLOR_WHITESMOKE \
	cgi_glColor4d(CGI_COLOR_WHITESMOKE_RED, \
			CGI_COLOR_WHITESMOKE_GREEN, \
			CGI_COLOR_WHITESMOKE_BLUE, \
			CGI_COLOR_WHITESMOKE_ALPHA)

#define CGI_COLOR_SEASHELL \
	cgi_glColor4d(CGI_COLOR_SEASHELL_RED, \
			CGI_COLOR_SEASHELL_GREEN, \
			CGI_COLOR_SEASHELL_BLUE, \
			CGI_COLOR_SEASHELL_ALPHA)

#define CGI_COLOR_BEIGE \
	cgi_glColor4d(CGI_COLOR_BEIGE_RED, \
			CGI_COLOR_BEIGE_GREEN, \
			CGI_COLOR_BEIGE_BLUE, \
			CGI_COLOR_BEIGE_ALPHA)

#define CGI_COLOR_OLDLACE \
	cgi_glColor4d(CGI_COLOR_OLDLACE_RED, \
			CGI_COLOR_OLDLACE_GREEN, \
			CGI_COLOR_OLDLACE_BLUE, \
			CGI_COLOR_OLDLACE_ALPHA)

#define CGI_COLOR_FLORALWHITE \
	cgi_glColor4d(CGI_COLOR_FLORALWHITE_RED, \
			CGI_COLOR_FLORALWHITE_GREEN, \
			CGI_COLOR_FLORALWHITE_BLUE, \
			CGI_COLOR_FLORALWHITE_ALPHA)

#define CGI_COLOR_IVORY \
	cgi_glColor4d(CGI_COLOR_IVORY_RED, \
			CGI_COLOR_IVORY_GREEN, \
			CGI_COLOR_IVORY_BLUE, \
			CGI_COLOR_IVORY_ALPHA)

#define CGI_COLOR_ANTIQUEWHITE \
	cgi_glColor4d(CGI_COLOR_ANTIQUEWHITE_RED, \
			CGI_COLOR_ANTIQUEWHITE_GREEN, \
			CGI_COLOR_ANTIQUEWHITE_BLUE, \
			CGI_COLOR_ANTIQUEWHITE_ALPHA)

#define CGI_COLOR_LINEN \
	cgi_glColor4d(CGI_COLOR_LINEN_RED, \
			CGI_COLOR_LINEN_GREEN, \
			CGI_COLOR_LINEN_BLUE, \
			CGI_COLOR_LINEN_ALPHA)

#define CGI_COLOR_LAVENDERBLUSH \
	cgi_glColor4d(CGI_COLOR_LAVENDERBLUSH_RED, \
			CGI_COLOR_LAVENDERBLUSH_GREEN, \
			CGI_COLOR_LAVENDERBLUSH_BLUE, \
			CGI_COLOR_LAVENDERBLUSH_ALPHA)

#define CGI_COLOR_MISTYROSE \
	cgi_glColor4d(CGI_COLOR_MISTYROSE_RED, \
			CGI_COLOR_MISTYROSE_GREEN, \
			CGI_COLOR_MISTYROSE_BLUE, \
			CGI_COLOR_MISTYROSE_ALPHA)

// grey colors

#define CGI_COLOR_GAINSBORO \
	cgi_glColor4d(CGI_COLOR_GAINSBORO_RED, \
			CGI_COLOR_GAINSBORO_GREEN, \
			CGI_COLOR_GAINSBORO_BLUE, \
			CGI_COLOR_GAINSBORO_ALPHA)

#define CGI_COLOR_LIGHTGREY \
	cgi_glColor4d(CGI_COLOR_LIGHTGREY_RED, \
			CGI_COLOR_LIGHTGREY_GREEN, \
			CGI_COLOR_LIGHTGREY_BLUE, \
			CGI_COLOR_LIGHTGREY_ALPHA)

#define CGI_COLOR_SILVER \
	cgi_glColor4d(CGI_COLOR_SILVER_RED, \
			CGI_COLOR_SILVER_GREEN, \
			CGI_COLOR_SILVER_BLUE, \
			CGI_COLOR_SILVER_ALPHA)

#define CGI_COLOR_DARKGRAY \
	cgi_glColor4d(CGI_COLOR_DARKGRAY_RED, \
			CGI_COLOR_DARKGRAY_GREEN, \
			CGI_COLOR_DARKGRAY_BLUE, \
			CGI_COLOR_DARKGRAY_ALPHA)

#define CGI_COLOR_GRAY \
	cgi_glColor4d(CGI_COLOR_GRAY_RED, \
			CGI_COLOR_GRAY_GREEN, \
			CGI_COLOR_GRAY_BLUE, \
			CGI_COLOR_GRAY_ALPHA)

#define CGI_COLOR_DIMGRAY \
	cgi_glColor4d(CGI_COLOR_DIMGRAY_RED, \
			CGI_COLOR_DIMGRAY_GREEN, \
			CGI_COLOR_DIMGRAY_BLUE, \
			CGI_COLOR_DIMGRAY_ALPHA)

#define CGI_COLOR_LIGHTSLATEGRAY \
	cgi_glColor4d(CGI_COLOR_LIGHTSLATEGRAY_RED, \
			CGI_COLOR_LIGHTSLATEGRAY_GREEN, \
			CGI_COLOR_LIGHTSLATEGRAY_BLUE, \
			CGI_COLOR_LIGHTSLATEGRAY_ALPHA)

#define CGI_COLOR_SLATEGRAY \
	cgi_glColor4d(CGI_COLOR_SLATEGRAY_RED, \
			CGI_COLOR_SLATEGRAY_GREEN, \
			CGI_COLOR_SLATEGRAY_BLUE, \
			CGI_COLOR_SLATEGRAY_ALPHA)

#define CGI_COLOR_DARKSLATEGRAY \
	cgi_glColor4d(CGI_COLOR_DARKSLATEGRAY_RED, \
			CGI_COLOR_DARKSLATEGRAY_GREEN, \
			CGI_COLOR_DARKSLATEGRAY_BLUE, \
			CGI_COLOR_DARKSLATEGRAY_ALPHA)

#define CGI_COLOR_BLACK \
	cgi_glColor4d(CGI_COLOR_BLACK_RED, \
			CGI_COLOR_BLACK_GREEN, \
			CGI_COLOR_BLACK_BLUE, \
			CGI_COLOR_BLACK_ALPHA)


#if defined(__cplusplus)
};
#endif // __cplusplus

#endif // _ASGARD_CORE_COLORS_H

