/*
 * keys.h
 *
 * Copyright (C) 2008 - 2011 by Joshua S. English. This document is the
 * intellectual property of Joshua S. English, all rights reserved.
 *
 * The set of keyboard keys for the Asgard Game Engine, header file.
 *
 * Written by Josh English.
 */

#if !defined(_ASGARD_CORE_KEYS_H)

#define _ASGARD_CORE_KEYS_H

#if !defined(_ASGARD_H) && !defined(_ASGARD_CORE_COMPONENT)
#	error "Incorrect use of this header file."
#endif // _ASGARD_H || _ASGARD_CORE_COMPONENT

#if defined(__cplusplus)
extern "C" {
#endif // __cplusplus


// define keys public constants

typedef enum _AsgardKeys {
	ASGARD_KEY_BACKSPACE = OS_KEY_BACKSPACE,
	ASGARD_KEY_TAB = OS_KEY_TAB,
	ASGARD_KEY_CLEAR = OS_KEY_CLEAR,
	ASGARD_KEY_RETURN = OS_KEY_RETURN,
	ASGARD_KEY_SHIFT = OS_KEY_SHIFT,
	ASGARD_KEY_CONTROL = OS_KEY_CONTROL,
	ASGARD_KEY_CAPS_LOCK = OS_KEY_CAPS_LOCK,
	ASGARD_KEY_ESCAPE = OS_KEY_ESCAPE,
	ASGARD_KEY_SPACE = OS_KEY_SPACE,
	ASGARD_KEY_PAGE_UP = OS_KEY_PAGE_UP,
	ASGARD_KEY_PAGE_DOWN = OS_KEY_PAGE_DOWN,
	ASGARD_KEY_HOME = OS_KEY_HOME,
	ASGARD_KEY_END = OS_KEY_END,
	ASGARD_KEY_UP = OS_KEY_UP,
	ASGARD_KEY_DOWN = OS_KEY_DOWN,
	ASGARD_KEY_LEFT = OS_KEY_LEFT,
	ASGARD_KEY_RIGHT = OS_KEY_RIGHT,
	ASGARD_KEY_SELECT = OS_KEY_SELECT,
	ASGARD_KEY_PRINT = OS_KEY_PRINT,
	ASGARD_KEY_EXECUTE = OS_KEY_EXECUTE,
	ASGARD_KEY_PRINT_SCREEN = OS_KEY_PRINT_SCREEN,
	ASGARD_KEY_INSERT = OS_KEY_INSERT,
	ASGARD_KEY_DELETE = OS_KEY_DELETE,

	ASGARD_KEY_NP_0 = OS_KEY_NP_0,
	ASGARD_KEY_NP_1 = OS_KEY_NP_1,
	ASGARD_KEY_NP_2 = OS_KEY_NP_2,
	ASGARD_KEY_NP_3 = OS_KEY_NP_3,
	ASGARD_KEY_NP_4 = OS_KEY_NP_4,
	ASGARD_KEY_NP_5 = OS_KEY_NP_5,
	ASGARD_KEY_NP_6 = OS_KEY_NP_6,
	ASGARD_KEY_NP_7 = OS_KEY_NP_7,
	ASGARD_KEY_NP_8 = OS_KEY_NP_8,
	ASGARD_KEY_NP_9 = OS_KEY_NP_9,
	ASGARD_KEY_NP_ADD = OS_KEY_NP_ADD,
	ASGARD_KEY_NP_SUBTRACT = OS_KEY_NP_SUBTRACT,
	ASGARD_KEY_NP_MULTIPLY = OS_KEY_NP_MULTIPLY,
	ASGARD_KEY_NP_DIVIDE = OS_KEY_NP_DIVIDE,
	ASGARD_KEY_NP_DECIMAL = OS_KEY_NP_DECIMAL,

	ASGARD_KEY_F1 = OS_KEY_F1,
	ASGARD_KEY_F2 = OS_KEY_F2,
	ASGARD_KEY_F3 = OS_KEY_F3,
	ASGARD_KEY_F4 = OS_KEY_F4,
	ASGARD_KEY_F5 = OS_KEY_F5,
	ASGARD_KEY_F6 = OS_KEY_F6,
	ASGARD_KEY_F7 = OS_KEY_F7,
	ASGARD_KEY_F8 = OS_KEY_F8,
	ASGARD_KEY_F9 = OS_KEY_F9,
	ASGARD_KEY_F10 = OS_KEY_F10,
	ASGARD_KEY_F11 = OS_KEY_F11,
	ASGARD_KEY_F12 = OS_KEY_F12,

	ASGARD_KEY_0 = OS_KEY_0,
	ASGARD_KEY_1 = OS_KEY_1,
	ASGARD_KEY_2 = OS_KEY_2,
	ASGARD_KEY_3 = OS_KEY_3,
	ASGARD_KEY_4 = OS_KEY_4,
	ASGARD_KEY_5 = OS_KEY_5,
	ASGARD_KEY_6 = OS_KEY_6,
	ASGARD_KEY_7 = OS_KEY_7,
	ASGARD_KEY_8 = OS_KEY_8,
	ASGARD_KEY_9 = OS_KEY_9,

	ASGARD_KEY_A = OS_KEY_A,
	ASGARD_KEY_B = OS_KEY_B,
	ASGARD_KEY_C = OS_KEY_C,
	ASGARD_KEY_D = OS_KEY_D,
	ASGARD_KEY_E = OS_KEY_E,
	ASGARD_KEY_F = OS_KEY_F,
	ASGARD_KEY_G = OS_KEY_G,
	ASGARD_KEY_H = OS_KEY_H,
	ASGARD_KEY_I = OS_KEY_I,
	ASGARD_KEY_J = OS_KEY_J,
	ASGARD_KEY_K = OS_KEY_K,
	ASGARD_KEY_L = OS_KEY_L,
	ASGARD_KEY_M = OS_KEY_M,
	ASGARD_KEY_N = OS_KEY_N,
	ASGARD_KEY_O = OS_KEY_O,
	ASGARD_KEY_P = OS_KEY_P,
	ASGARD_KEY_Q = OS_KEY_Q,
	ASGARD_KEY_R = OS_KEY_R,
	ASGARD_KEY_S = OS_KEY_S,
	ASGARD_KEY_T = OS_KEY_T,
	ASGARD_KEY_U = OS_KEY_U,
	ASGARD_KEY_V = OS_KEY_V,
	ASGARD_KEY_W = OS_KEY_W,
	ASGARD_KEY_X = OS_KEY_X,
	ASGARD_KEY_Y = OS_KEY_Y,
	ASGARD_KEY_Z = OS_KEY_Z,

	ASGARD_KEY_END_OF_LIST = -1001,
} AsgardKeys;


#if defined(__cplusplus)
};
#endif // __cplusplus

#endif // _ASGARD_CORE_KEYS_H

